### ISSUE TITLE
Modbus serial RTS support

### ISSUE THREAD

**Issue by Aleshus** [BiancoRoyal/node-red-contrib-modbus#123]
## Feature
 - ( x) feature request
 
 **What is the motivation / use case for changing the behavior?**
some RPi HATs need to change RTS pin when read or write to the RS485 bus. Can you add configuration support for that? Similar as the node-red-contrib-serialport-rs485 where autswitch RTS/DTR is implemented.

Thanks,
Aleš

**Comment by wazza-b** [comment]
Encountered a need for this when using MAX485 based boards and also a Beaglebone 'RS485 CAN CAPE'. Ideally be able to define which gpio are used for DE/RE, and it's also possible to tie them together and use one pin. Happy to sponsor if I can figure out how...

**Comment by biancode** [comment]
@wazza-b sponsoring could be done by lines of code the best, here on GitHub Sponsoring or here: [Sponsoring](https://bianco-royal.com/supporter.html)
