### ISSUE TITLE
[Question] Reading from Master

### ISSUE THREAD

**Issue by Sineos** [BiancoRoyal/node-red-contrib-modbus#148]
My setup:
- A PLC acting as Master
- A `Modbus Server` Node 
- A `Modbus Read` Node

My understanding:
- The Master (PLC) connects to the the Slave (Server Node)
- The Master pushes its registers to the Slave
- The Read Node reads the relevant registers from the Server

This works and I can get the data for further processing in the flow.

I would think that the Slave gets the data basically in real time but for processing of the data in the flow, I need to regularly pull the server.

Is there a way to have the `Modbus Server` Node actively pushing new data down the flow or is my understanding of the concept false?

**Comment by biancode** [comment]
Hi @Sineos, Modbus is polling take a look here [Modbus.org](http://modbus.org/tech.php)

**Comment by biancode** [comment]
You could build some with Node-RED and the context inside Node-RED to watch values and to send events on value changes. Does it clearify your question?

**Comment by Sineos** [comment]
@biancode many thanks for coming back on this. 

Do I understand this correctly that the Slave/Server is polling the Master/Client?

**Comment by jason-turner2** [comment]
Hi @Sineos . In Modbus, the Server cannot initiate the exchange, so it does not poll. But you can put a Modbus client on the same Node Red flow as the server, and have the new client do the extra polling in order to push the processing if you need to. I hope I've answered your question. If not, please feel free to ask.

**Comment by biancode** [comment]
reopen if you need more
