### ISSUE TITLE
Writing to Flex Server Buffers with Message

### ISSUE THREAD

**Issue by jackmarshall9357** [BiancoRoyal/node-red-contrib-modbus#149]
**I'm submitting a ...**  (check one with "x")

## Support/Advice
 - support/advice request => **Please do not submit support requests here**, instead use [the link to our support page](https://bianco-royal.cloud/supporter/#/content/backer), please!

## Feature
 - ( ) feature request
 
 **What is the motivation / use case for changing the behavior?**
 

## Simple question to get some hint
 - ( ) simple question => please visit the Wiki, the YouTube tutorials and the Info tab by clicking on the node inside Node-RED before
 - ( ) help wanted => you read all information and watched relevant YouTube tutorials, but you need more help

## Problem
 - ( ) bug report => please search github for a similar issue or PR and test Modbus problems with the [modbus-serial](https://github.com/yaacov/node-modbus-serial) package before submitting
 - (x) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
 
 When trying to write values (with a message) to a Flex Server node I get no response or change in the servers buffers. I also get no error.
 
 **Expected behavior**
 
 i would Expect Either an Error if the payload is in the wrong format, or if correct the valuess of th buffers to change.
 **Minimal reproduction of the problem with instructions**
 
   1. Flow with problem
   `[
    {
        "id": "7c901ce1.97f324",
        "type": "tab",
        "label": "Flow 3",
        "disabled": false,
        "info": ""
    },
    {
        "id": "9f1c31db.f86f2",
        "type": "inject",
        "z": "7c901ce1.97f324",
        "name": "",
        "topic": "",
        "payload": "[0]",
        "payloadType": "bin",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 170,
        "y": 160,
        "wires": [
            [
                "fcd0afb0.7a1cf"
            ]
        ]
    },
    {
        "id": "fa376833.7c3268",
        "type": "inject",
        "z": "7c901ce1.97f324",
        "name": "",
        "topic": "",
        "payload": "[1]",
        "payloadType": "bin",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 170,
        "y": 200,
        "wires": [
            [
                "fcd0afb0.7a1cf"
            ]
        ]
    },
    {
        "id": "6e630377.f85cdc",
        "type": "modbus-flex-server",
        "z": "7c901ce1.97f324",
        "name": "",
        "logEnabled": true,
        "serverAddress": "0.0.0.0",
        "serverPort": 11502,
        "responseDelay": "0",
        "unitId": 1,
        "delayUnit": "ms",
        "coilsBufferSize": "2",
        "registersBufferSize": "2",
        "minAddress": 0,
        "splitAddress": "1",
        "funcGetCoil": "function getFlexCoil(addr, unitID) {\n\tif (unitID === node.unitId && \n\t\taddr >= node.minAddress && \n\t\taddr <= node.splitAddress) { \n\n\t\treturn node.coils.readUInt8(addr * node.bufferFactor) \n\t}  \n}",
        "funcGetDiscreteInput": "function getFlexDiscreteInput(addr, unitID) {\n\taddr += node.splitAddress\n\tif (unitID === node.unitId && \n\t\taddr > node.splitAddress && \n\t\taddr <= node.splitAddress * 2) { \n\n\t\treturn node.coils.readUInt8(addr * node.bufferFactor) \n\t}  \n}",
        "funcGetInputRegister": "function getFlexInputRegister(addr, unitID) { \n\tif (unitID === node.unitId && \n\t\taddr >= node.minAddress && \n\t\taddr <= node.splitAddress) { \n\n\t\treturn node.registers.readUInt16BE(addr * node.bufferFactor)  \n\t} \n}",
        "funcGetHoldingRegister": "function getFlexHoldingRegsiter(addr, unitID) { \n\taddr += node.splitAddress\n\tif (unitID === node.unitId && \n\t\taddr >= node.splitAddress && \n\t\taddr <= node.splitAddress * 2) { \n\n\t\treturn node.registers.readUInt16BE(addr * node.bufferFactor)  \n\t} \n}",
        "funcSetCoil": "function setFlexCoil(addr, value, unitID) { \n\tif (unitID === node.unitId && \n\t\taddr >= node.minAddress && \n\t\taddr <= node.splitAddress) { \n\n\t\tnode.coils.writeUInt8(value, addr * node.bufferFactor)  \n\t} \n}",
        "funcSetRegister": "function setFlexRegister(addr, value, unitID) { \n\taddr += node.splitAddress\n\tif (unitID === node.unitId && \n\t\taddr >= node.splitAddress && \n\t\taddr <= node.splitAddress * 2) { \n\n\t\tnode.registers.writeUInt16BE(value, addr * node.bufferFactor)  \n\t} \n}",
        "showErrors": true,
        "x": 600,
        "y": 220,
        "wires": [
            [
                "d3191ed7.41aaa"
            ],
            [
                "d3191ed7.41aaa"
            ],
            [
                "d3191ed7.41aaa"
            ],
            [
                "d3191ed7.41aaa"
            ]
        ]
    },
    {
        "id": "765d9965.35e9f8",
        "type": "modbus-read",
        "z": "7c901ce1.97f324",
        "name": "",
        "topic": "",
        "showStatusActivities": false,
        "logIOActivities": false,
        "showErrors": false,
        "unitid": "1",
        "dataType": "Coil",
        "adr": "0",
        "quantity": "1",
        "rate": "2",
        "rateUnit": "s",
        "delayOnStart": false,
        "startDelayTime": "",
        "server": "107a712.bb19d8f",
        "useIOFile": false,
        "ioFile": "",
        "useIOForPayload": false,
        "x": 360,
        "y": 500,
        "wires": [
            [],
            [
                "beaf440f.78db88"
            ]
        ]
    },
    {
        "id": "beaf440f.78db88",
        "type": "modbus-response",
        "z": "7c901ce1.97f324",
        "name": "",
        "registerShowMax": 20,
        "x": 600,
        "y": 500,
        "wires": []
    },
    {
        "id": "d3191ed7.41aaa",
        "type": "debug",
        "z": "7c901ce1.97f324",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 870,
        "y": 220,
        "wires": []
    },
    {
        "id": "fcd0afb0.7a1cf",
        "type": "function",
        "z": "7c901ce1.97f324",
        "name": "",
        "func": "let value = msg.payload;\nmsg.payload = {\n    register:'discrete', \n    address: 0,\n    value:value\n}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 350,
        "y": 220,
        "wires": [
            [
                "4ace8df4.f5aad4",
                "6e630377.f85cdc"
            ]
        ]
    },
    {
        "id": "4ace8df4.f5aad4",
        "type": "debug",
        "z": "7c901ce1.97f324",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 500,
        "y": 140,
        "wires": []
    },
    {
        "id": "d67fb0e5.0b342",
        "type": "catch",
        "z": "7c901ce1.97f324",
        "name": "",
        "scope": null,
        "uncaught": false,
        "x": 300,
        "y": 80,
        "wires": [
            [
                "6638eb77.248df4"
            ]
        ]
    },
    {
        "id": "6638eb77.248df4",
        "type": "debug",
        "z": "7c901ce1.97f324",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 500,
        "y": 80,
        "wires": []
    },
    {
        "id": "372afec5.89a8a2",
        "type": "inject",
        "z": "7c901ce1.97f324",
        "name": "",
        "topic": "",
        "payload": "1",
        "payloadType": "num",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 170,
        "y": 420,
        "wires": [
            [
                "7ffa4e9f.bc77d"
            ]
        ]
    },
    {
        "id": "74e917e.dff21e8",
        "type": "inject",
        "z": "7c901ce1.97f324",
        "name": "",
        "topic": "",
        "payload": "0",
        "payloadType": "num",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 170,
        "y": 380,
        "wires": [
            [
                "7ffa4e9f.bc77d"
            ]
        ]
    },
    {
        "id": "7ffa4e9f.bc77d",
        "type": "modbus-write",
        "z": "7c901ce1.97f324",
        "name": "",
        "showStatusActivities": false,
        "showErrors": false,
        "unitid": "1",
        "dataType": "Coil",
        "adr": "0",
        "quantity": "1",
        "server": "107a712.bb19d8f",
        "x": 400,
        "y": 400,
        "wires": [
            [],
            [
                "c8adae9.6fe7b5"
            ]
        ]
    },
    {
        "id": "c8adae9.6fe7b5",
        "type": "modbus-response",
        "z": "7c901ce1.97f324",
        "name": "",
        "registerShowMax": 20,
        "x": 620,
        "y": 400,
        "wires": []
    },
    {
        "id": "7435b2bb.17cf5c",
        "type": "inject",
        "z": "7c901ce1.97f324",
        "name": "",
        "topic": "",
        "payload": "1",
        "payloadType": "num",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 170,
        "y": 280,
        "wires": [
            [
                "fcd0afb0.7a1cf"
            ]
        ]
    },
    {
        "id": "349d85a2.8ca8aa",
        "type": "inject",
        "z": "7c901ce1.97f324",
        "name": "",
        "topic": "",
        "payload": "0",
        "payloadType": "num",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 170,
        "y": 240,
        "wires": [
            [
                "fcd0afb0.7a1cf"
            ]
        ]
    },
    {
        "id": "89d03e42.bd429",
        "type": "modbus-read",
        "z": "7c901ce1.97f324",
        "name": "",
        "topic": "",
        "showStatusActivities": false,
        "logIOActivities": false,
        "showErrors": false,
        "unitid": "1",
        "dataType": "Input",
        "adr": "0",
        "quantity": "1",
        "rate": "2",
        "rateUnit": "s",
        "delayOnStart": false,
        "startDelayTime": "",
        "server": "107a712.bb19d8f",
        "useIOFile": false,
        "ioFile": "",
        "useIOForPayload": false,
        "x": 350,
        "y": 620,
        "wires": [
            [],
            [
                "1a30fc54.2eced4"
            ]
        ]
    },
    {
        "id": "1a30fc54.2eced4",
        "type": "modbus-response",
        "z": "7c901ce1.97f324",
        "name": "",
        "registerShowMax": 20,
        "x": 590,
        "y": 620,
        "wires": []
    },
    {
        "id": "107a712.bb19d8f",
        "type": "modbus-client",
        "z": "",
        "name": "",
        "clienttype": "tcp",
        "bufferCommands": true,
        "stateLogEnabled": false,
        "tcpHost": "127.0.0.1",
        "tcpPort": "11502",
        "tcpType": "DEFAULT",
        "serialPort": "/dev/ttyUSB",
        "serialType": "RTU-BUFFERD",
        "serialBaudrate": "9600",
        "serialDatabits": "8",
        "serialStopbits": "1",
        "serialParity": "none",
        "serialConnectionDelay": "100",
        "unit_id": "1",
        "commandDelay": "1",
        "clientTimeout": "1000",
        "reconnectTimeout": "2000"
    }
]`

### Your Environment
**Please tell us about your environment:**

  * (x) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) package global from source (using git clone)
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) as a global package (using npm i -g)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    
    - ( ) macOS: v 
    - (x) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   : node-red-contrib-modbus
     - Version: 4.1.3
     - Vendor :
     - Link   : https://
     
    
* **node-red-contrib-modbus version:** `4.1.3`

* **Node:** (min. 6.x)
   `node --version` = `10.15.3`

**Comment by biancode** [comment]
Hi, there is no way to send data directly to the server input. You have to use the read/write operations via modbus here. You could work with the Node-RED context, but this is not implemented for now and would be a feature request.
Happy wiring!

**Comment by jackmarshall9357** [comment]
Hi thanks for the Reply, I get using the Node-Red Context but to me at least it makes more sense to do this with a msg directly into the server?  

But without either feature it is impossible to write into the 2 Buffers (Discrete Inputs, and Holding Registers) that you can't use Modbus to write into, which makes having them present on the server rather redundant? it also makes it impossible to use the server in the scenario of providing Read Only Values.

but PR #140 should make writing in via msg work? I was hoping that there was a test implementation I could see, but as you can see from the flow I submitted got nothing in the way of feedback or errors. Would you be happy with a new PR to write in via msg to the flex-server input?

**Comment by biancode** [comment]
Oh, I forgot this change, sorry ... then we should reopen this one.

**Comment by biancode** [comment]
PR #140 released with 5.1.0

**Comment by biancode** [comment]
![image](https://user-images.githubusercontent.com/4369867/70068553-7bb4c400-15f0-11ea-8ce9-e2fc0fad7027.png)
