### ISSUE TITLE
Modbus RTU error

### ISSUE THREAD

**Issue by bligher** [BiancoRoyal/node-red-contrib-modbus#150]
## Simple question to get some hint
 - (x) help wanted => you read all information and watched relevant YouTube tutorials, but you need more help

 **Current behavior**
We want to read and write binary values. Everything works with the Windows program Modbus Slave. It does not work with Node-RED yet. It shows "error Data lenght error, expected 6 got 8".
We have already tried RTU Buffered. Where is the problem or what have I done wrong?

Modbus configuration 19200, 8 Data, 1 Stop, Parity even
[Master](https://ibb.co/7tXSCKJ)
[Slave RPI](https://ibb.co/y47tsBG)

Modbus with Modbus Slave Windows
[Master](https://ibb.co/y6dnZdz)
[Slave MBSlave](https://ibb.co/q9nx44R)

Modbus with Modbus Slave Node-RED
[Master](https://ibb.co/y6dnZdz)
[Slave RPI](https://ibb.co/jrCjkgB)

Flow: `[{"id":"190f755f.48477b","type":"modbus-read","z":"8997f336.b7a4b","name":"","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"2","dataType":"Input","adr":"0","quantity":"1","rate":"1","rateUnit":"s","delayOnStart":false,"startDelayTime":"1","server":"70f6fca3.cfcc04","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":210,"y":140,"wires":[["618fe308.2d124c"],["e45f7abd.c12bf8"]]},{"id":"70f6fca3.cfcc04","type":"modbus-client","z":"","name":"USBRS485","clienttype":"simpleser","bufferCommands":true,"stateLogEnabled":false,"tcpHost":"127.0.0.1","tcpPort":"502","tcpType":"DEFAULT","serialPort":"/dev/ttyUSB0","serialType":"RTU","serialBaudrate":"19200","serialDatabits":"8","serialStopbits":"1","serialParity":"even","serialConnectionDelay":"500","unit_id":"1","commandDelay":"","clientTimeout":"1000","reconnectTimeout":"2000"}]`

### Your Environment
Raspberry Pi 3 Model B+ (Slave) connect with a [USB-RS485 Cable](https://www.ftdichip.com/Support/Documents/DataSheets/Cables/DS_USB_RS485_CABLES.pdf) to [Sauter ecos 504](https://www.sauter-controls.com/wp-content/uploads/2019/02/1024712.pdf) (Master)
Node-RED 0.20.7
node-red-contrib-modbus 4.1.3
Both Side with Termination Resistor

  * Device :
    - Raspbian buster

**Comment by biancode** [comment]
maybe duplicate to #146
