### ISSUE TITLE
UnhandledPromiseRejectionWarning after upgrading to Node-Red 1.0.0

### ISSUE THREAD

**Issue by trenty27** [BiancoRoyal/node-red-contrib-modbus#154]
**I'm submitting a ...**  (check one with "x")

## Problem
 - (x) bug report => no related issues found in github for modbus serial

 **Current behavior**
I had a perfectly working flow implementing modbus communication to a Vallox ventilation system. After upgrading Node-Red to version 1.0.0, the flow stopped working. Modbus read does not succeed anymore, and for every attempted modbus read, an error message appears on the log:
(node:27964) UnhandledPromiseRejectionWarning: TypeError: a is not a function
    at activateSending (/home/pi/.node-red/node_modules/node-red-contrib-modbus/modbus/maps/modbus-client.js:587:20)
(node:27964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 719)

 **Expected behavior**
 The modbus communication is successful as before upgrading to node-red 1.0.0
 
 **Minimal reproduction of the problem with instructions**
The problem can be reproduced by upgrading Node-Red to V1.0.0 and using the simplyfied flow:
```
[{"id":"fe9fab66.e14938","type":"tab","label":"Vallox","disabled":false,"info":""},{"id":"15dc5136.f68e2f","type":"modbus-getter","z":"fe9fab66.e14938","name":"STATE 4609","showStatusActivities":true,"showErrors":false,"logIOActivities":false,"unitid":"","dataType":"HoldingRegister","adr":"4609","quantity":"1","server":"2a7f376e.342c08","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":290,"y":140,"wires":[[],["7222f114.6b0b4"]]},{"id":"409696e3.c0ce68","type":"inject","z":"fe9fab66.e14938","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":140,"wires":[["15dc5136.f68e2f"]]},{"id":"7222f114.6b0b4","type":"modbus-response","z":"fe9fab66.e14938","name":"","registerShowMax":20,"x":489.5,"y":141,"wires":[]},{"id":"2a7f376e.342c08","type":"modbus-client","z":"","name":"Vallox","clienttype":"simpleser","bufferCommands":true,"stateLogEnabled":false,"tcpHost":"127.0.0.1","tcpPort":"502","tcpType":"DEFAULT","serialPort":"/dev/ttyUSB2","serialType":"RTU","serialBaudrate":"19200","serialDatabits":"8","serialStopbits":"1","serialParity":"none","serialConnectionDelay":"100","unit_id":1,"commandDelay":1,"clientTimeout":1000,"reconnectTimeout":2000}]
```
to attemp a modbus read on one register.

### Your Environment
**Please tell us about your environment:**

Raspberry pi 3 running Node-Red v1.0.0, connected to a Vallox Valloplus 350 MV Ventilation Unit (Modbus RTU) using a RS485 USB Dongle.

  * (x) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
├─┬ node-red-contrib-modbus@4.1.3
│...
│ ├─┬ modbus-serial@7.5.1
│ │ ├─┬ debug@4.1.1
│ │ │ └── ms@2.1.2
│ │ └── serialport@7.1.5 deduped
│ ├─┬ serialport@7.1.4
│...

  * Device :
    - (X ) Raspbian: VERSION="9 (stretch)"
 
   * Description of the connecting Modbus system:
   
     - Name   : Vallox ValloPlus
     - Version: 350 MV
     - Vendor : Vallox
     - Link   : https://oxomi.com/service/json/catalog/pdf?portal=3000306&user=&roles=&accessToken=&catalog=10136204
Modbus description: https://www.vallox.com/files/1092/Manual_Modbus_ENG_20190215_PRINT.pdf
     
  
* **node-red-contrib-modbus version:** ``
4.1.3

* **Node:** (min. 6.x)
   `node --version` = v10.16.3

**Comment by biancode** [comment]
#144
