### ISSUE TITLE
how to give host IP and port from function node when using Modbus Flex getter

### ISSUE THREAD

**Issue by Kartheek1512** [BiancoRoyal/node-red-contrib-modbus#159]
Hi, 

 I have  25 modbus slaves with different IP address in a network. Each slave talks modbus TCp/IP. I want to get a same set of registers from each slave.  i can use 25 "modbus flex getter" nodes but i had problems doing that before. Is there a way to send the host/slave IP address to the "modbus flex getter" node via a function node?  That would help me a lot. Can anyone please help.

**Comment by biancode** [comment]
Hi,

please give the Modbus Flex Connector a try!
