### ISSUE TITLE
Broadcast support for serial mode

### ISSUE THREAD

**Issue by boraozgen** [BiancoRoyal/node-red-contrib-modbus#195]
**I'm submitting a ...**

## Feature
 - (x) feature request
 
 **What is the motivation / use case for changing the behavior?**
Broadcast messages with Unit ID = 0 should be supported for serial mode. The master should not expect a response in case of a broadcast message.

This behavior is documented on page 7 of the spec:
http://www.modbus.org/docs/Modbus_over_serial_line_V1_02.pdf

**Comment by biancode** [comment]
Todo: [Modbus-Serial-Lib Check for UnitID 0](https://www.npmjs.com/package/modbus-serial )

**Comment by biancode** [comment]
Todo: UnitID checking on flex nodes ( false vs. 0 needs to be number for UnitID)

**Comment by biancode** [comment]
Todo: unit tests for UnitID 0

**Comment by biancode** [comment]
https://github.com/BiancoRoyal/node-red-contrib-modbus/projects/4#card-38085398

**Comment by biancode** [comment]
Please, send unstable PR's to branch develop!

**Comment by biancode** [comment]
first release with v5.13.0

**Comment by biancode** [comment]
@boraozgen could you test with v5.13.2 on multiple devices or with the Modbus Simulator for PC and serial connections? I get no response from broadcasts via UnitId 0.

**Comment by boraozgen** [comment]
You are not supposed to get any responses. From spec:

> In broadcast mode, the master can send a request to all slaves. No response is returned to broadcast requests sent by the master.  The broadcast requests are necessarily writing commands.  All devices must accept the broadcast for writing function.  The address 0 is reserved to identify a broadcast exchange.

**Comment by boraozgen** [comment]
Closing the issue as it works as of v5.13.1 for my setup.

**Comment by biancode** [comment]
@boraozgen thanks for your contribution :)
