### ISSUE TITLE
Version 5.11.0 is not published on flows.nodered.org

### ISSUE THREAD

**Issue by mikeS7** [BiancoRoyal/node-red-contrib-modbus#197]
Update mechanism on flows.nodered.org is changed, could you please manually update version on flows.nodered.org

Details can be found in the guide: [Adding to flows.nodered.org](https://nodered.org/docs/creating-nodes/packaging#adding-to-flowsnoderedorg)

Thank you!

**Comment by Ekristoffe** [comment]
Done.
Seriously anyone can do it ....
