### ISSUE TITLE
Question: Is msg.input missing?

### ISSUE THREAD

**Issue by dudleyjosh** [BiancoRoyal/node-red-contrib-modbus#199]
I just updated to v5.11.0 and the 'Modbus Flex Getter' node is no longer passing the input message through (it used to get passed through as msg.input)?

Running node v12.16.1 on a RPi 3 running Raspian Stretch.

**Comment by biancode** [comment]
Please, try the new option 'keep msg properties' or build the input yourself. The new concept is merging msg data in the flows to kee property positions and to have less doubled properties. If you get in trouble with the new concept, then please describe it a bit more and fill out the issue template, please!

**Comment by biancode** [comment]
#194

**Comment by biancode** [comment]
reopen if there is more, please
