### ISSUE TITLE
Bug Sequential de-queuing 

### ISSUE THREAD

**Issue by cdriouech** [BiancoRoyal/node-red-contrib-modbus#202]
## Problem
 - (X) bug report => please search github for a similar issue or PR and test Modbus problems with the [modbus-serial](https://github.com/yaacov/node-modbus-serial) package before submitting
 - ( ) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
Blocking serial messages on Timeout and sequential queue.
 
 **Expected behavior**
It should not block the queue and every response should release with error if blocked.
 
 **Minimal reproduction of the problem with instructions**
 
   1.  serial device request per unit-id with connection and without
   2. send requests to them id by id
   3. timeout or reconnect will appear
   4. "sequential dequeue command not possible" error
   
### Your Environment
**Please tell us about your environment:**

  * ( ) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) package global from source (using git clone)
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) as a global package (using npm i -g)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    
    - ( ) macOS: v 
    - (X ) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   : Node RED
     - Version: v1.0.3
     - Vendor :
     - Link   : https://
    
* **node-red-contrib-modbus version:** v5.10.1

* **Node:** (min. x.x)
   `node --version` = v12.2.0

**Comment by biancode** [comment]
#195 is also interesting here to send only one msg to request all units

**Comment by mastrikGit** [comment]
I have same error with setup which worked for many monthes.
Started to appear after update to 5.12
Still happens with 5.13 after random time running 4hrs>

Here is part of flow:

`[{"id":"86604079.996eb","type":"mqtt out","z":"6cb719ba.d8bff8","name":"","topic":"","qos":"2","retain":"true","broker":"6f159f68.33fd","x":1130,"y":80,"wires":[]},{"id":"ad4a4b5f.87ae48","type":"rbe","z":"6cb719ba.d8bff8","name":"","func":"rbe","gap":"","start":"","inout":"out","property":"payload","x":910,"y":80,"wires":[["86604079.996eb"]]},{"id":"ec724b86.f33658","type":"inject","z":"6cb719ba.d8bff8","name":"","topic":"","payload":"","payloadType":"date","repeat":"0.2","crontab":"","once":true,"onceDelay":0.1,"x":110,"y":120,"wires":[["36d79240.bacaee"]]},{"id":"29ce1ddc.dd3252","type":"modbus-flex-getter","z":"6cb719ba.d8bff8","name":"","showStatusActivities":false,"showErrors":false,"logIOActivities":false,"server":"d54264c3.dde5e8","useIOFile":false,"ioFile":"","useIOForPayload":false,"emptyMsgOnFail":false,"keepMsgProperties":false,"x":550,"y":80,"wires":[["fbb339d2.bdbf18"],["f757d3c4.e0ab3"]]},{"id":"36d79240.bacaee","type":"function","z":"6cb719ba.d8bff8","name":"","func":"var msg1 = {topic:\"1-100\"};\nvar msg2 = {topic:\"101-200\"};\n\nmsg1.payload ={\n'fc': 3,\n'unitid': 1,\n'address': 1 ,\n'quantity': 100 }\n\nmsg2.payload ={\n'fc': 3,\n'unitid': 1,\n'address': 101 ,\n'quantity': 100 }\nreturn [[msg1,msg2]];","outputs":1,"noerr":0,"x":230,"y":80,"wires":[["7631ecad.7c8694"]]},{"id":"22d83040.2c9df","type":"comment","z":"6cb719ba.d8bff8","name":"Read from modbus","info":"","x":100,"y":40,"wires":[]},{"id":"fbb339d2.bdbf18","type":"function","z":"6cb719ba.d8bff8","name":"Map to local","func":"// build an array of msgs, mapping topics to registers\n\nswitch(msg.topic) {\n    case '1-100':\n    var msgs = [\n        { topic: \"Home/Light/Dimmer1/q\", payload: msg.payload[0] },\n        { topic: \"Home/Light/Dimmer1/command\", payload: msg.payload[1] },\n        { topic: \"Home/Light/Dimmer1/val\", payload: msg.payload[2] },\n        { topic: \"Home/Light/Dimmer2/q\", payload: msg.payload[3] },\n        { topic: \"Home/Light/Dimmer2/command\", payload: msg.payload[4] },\n        { topic: \"Home/Light/Dimmer2/val\", payload: msg.payload[5] },\n        { topic: \"Home/Light/Dimmer3/q\", payload: msg.payload[6] },\n        { topic: \"Home/Light/Dimmer3/command\", payload: msg.payload[7] },\n        { topic: \"Home/Light/Dimmer3/val\", payload: msg.payload[8] },\n        { topic: \"Home/Light/Dimmer4/q\", payload: msg.payload[9] },\n        { topic: \"Home/Light/Dimmer4/command\", payload: msg.payload[10] },\n        { topic: \"Home/Light/Dimmer4/val\", payload: msg.payload[11] },\n        { topic: \"Home/Light/Dimmer5/q\", payload: msg.payload[12] },\n        { topic: \"Home/Light/Dimmer5/command\", payload: msg.payload[13] },\n        { topic: \"Home/Light/Dimmer5/val\", payload: msg.payload[14] },\n        { topic: \"Home/Light/Dimmer6/q\", payload: msg.payload[15] },\n        { topic: \"Home/Light/Dimmer6/command\", payload: msg.payload[16] },\n        { topic: \"Home/Light/Dimmer6/val\", payload: msg.payload[17] },\n        { topic: \"Home/Light/Dimmer7/q\", payload: msg.payload[18] },\n        { topic: \"Home/Light/Dimmer7/command\", payload: msg.payload[19] },\n        { topic: \"Home/Light/Dimmer7/val\", payload: msg.payload[20] },\n        { topic: \"Home/Light/Dimmer8/q\", payload: msg.payload[21] },\n        { topic: \"Home/Light/Dimmer8/command\", payload: msg.payload[22] },\n        { topic: \"Home/Light/Dimmer8/val\", payload: msg.payload[23] },\n        { topic: \"Home/Light/Dimmer9/q\", payload: msg.payload[24] },\n        { topic: \"Home/Light/Dimmer9/command\", payload: msg.payload[25] },\n        { topic: \"Home/Light/Dimmer9/val\", payload: msg.payload[26] },\n        { topic: \"Home/Light/Dimmer10/q\", payload: msg.payload[27] },\n        { topic: \"Home/Light/Dimmer10/command\", payload: msg.payload[28] },\n        { topic: \"Home/Light/Dimmer10/val\", payload: msg.payload[29] }, \n        { topic: \"Home/Light/Dimmer11/q\", payload: msg.payload[30] },\n        { topic: \"Home/Light/Dimmer11/command\", payload: msg.payload[31] },   \n        { topic: \"Home/Light/Dimmer11/val\", payload: msg.payload[32] },\n        { topic: \"Home/Light/Dimmer12/q\", payload: msg.payload[33] },\n        { topic: \"Home/Light/Dimmer12/command\", payload: msg.payload[34] },\n        { topic: \"Home/Light/Dimmer12/val\", payload: msg.payload[35] },    \n        { topic: \"Home/Light/Dimmer13/q\", payload: msg.payload[36] },\n        { topic: \"Home/Light/Dimmer13/command\", payload: msg.payload[37] },    \n        { topic: \"Home/Light/Dimmer13/val\", payload: msg.payload[38] },\n        { topic: \"Home/Light/Dimmer14/q\", payload: msg.payload[39] },    \n        { topic: \"Home/Light/Dimmer14/command\", payload: msg.payload[40] },\n        { topic: \"Home/Light/Dimmer14/val\", payload: msg.payload[41] },    \n        { topic: \"Home/Light/Relay1/q\", payload: msg.payload[51] },\n        { topic: \"Home/Light/Relay1/command\", payload: msg.payload[52] },    \n        { topic: \"Home/Light/Relay2/q\", payload: msg.payload[53] },\n        { topic: \"Home/Light/Relay2/command\", payload: msg.payload[54] },\n        { topic: \"Home/Light/Relay3/q\", payload: msg.payload[55] },\n        { topic: \"Home/Light/Relay3/command\", payload: msg.payload[56] }, \n        { topic: \"Home/Light/Relay4/q\", payload: msg.payload[57] },\n        { topic: \"Home/Light/Relay4/command\", payload: msg.payload[58] }, \n        { topic: \"Home/Light/Relay5/q\", payload: msg.payload[59] },\n        { topic: \"Home/Light/Relay5/command\", payload: msg.payload[60] },\n        { topic: \"Home/Light/Relay6/q\", payload: msg.payload[61] },\n        { topic: \"Home/Light/Relay6/command\", payload: msg.payload[62] },\n        { topic: \"Home/Light/Relay7/q\", payload: msg.payload[63] },\n        { topic: \"Home/Light/Relay7/command\", payload: msg.payload[64] },\n        { topic: \"Home/Light/Relay8/q\", payload: msg.payload[65] },\n        { topic: \"Home/Light/Relay8/command\", payload: msg.payload[66] },\n        { topic: \"Home/Light/Relay9/q\", payload: msg.payload[67] },\n        { topic: \"Home/Light/Relay9/command\", payload: msg.payload[68] },\n        { topic: \"Home/Light/Relay10/q\", payload: msg.payload[69] },\n        { topic: \"Home/Light/Relay10/command\", payload: msg.payload[70] },\n        { topic: \"Home/Light/Relay11/q\", payload: msg.payload[71] },\n        { topic: \"Home/Light/Relay11/command\", payload: msg.payload[72] },\n        { topic: \"Home/Light/Relay12/q\", payload: msg.payload[73] },\n        { topic: \"Home/Light/Relay12/command\", payload: msg.payload[74] },        \n        { topic: \"Home/Light/LED1/q\", payload: msg.payload[81] },    \n        { topic: \"Home/Light/LED1/command\", payload: msg.payload[82] },\n        { topic: \"Home/Light/LED1/val\", payload: msg.payload[83] },\n        { topic: \"Home/Light/LED1/h\", payload: msg.payload[84] },\n        { topic: \"Home/Light/LED1/s\", payload: msg.payload[85] },\n        { topic: \"Home/Light/LED1/l\", payload: msg.payload[86] },   \n        { topic: \"Home/Light/LED1/w\", payload: msg.payload[87] },\n        { topic: \"Home/Light/LED2/q\", payload: msg.payload[88] },    \n        { topic: \"Home/Light/LED2/command\", payload: msg.payload[89] },\n        { topic: \"Home/Light/LED2/val\", payload: msg.payload[90] },\n        { topic: \"Home/Light/LED2/h\", payload: msg.payload[91] },\n        { topic: \"Home/Light/LED2/s\", payload: msg.payload[92] },\n        { topic: \"Home/Light/LED2/l\", payload: msg.payload[93] },   \n        { topic: \"Home/Light/LED2/w\", payload: msg.payload[94] },\n        { topic: \"Home/Light/LED3/q\", payload: msg.payload[95] },    \n        { topic: \"Home/Light/LED3/command\", payload: msg.payload[96] },\n        { topic: \"Home/Light/LED3/val\", payload: msg.payload[97] },\n        { topic: \"Home/Light/LED3/h\", payload: msg.payload[98] },\n        { topic: \"Home/Light/LED3/s\", payload: msg.payload[99] }\n        ];\n    break;\n    case '101-200':\n    var msgs = [\n        { topic: \"Home/Light/LED3/l\", payload: msg.payload[0] },   \n        { topic: \"Home/Light/LED3/w\", payload: msg.payload[1] },\n        { topic: \"Home/Light/LED4/q\", payload: msg.payload[2] },    \n        { topic: \"Home/Light/LED4/command\", payload: msg.payload[3] },\n        { topic: \"Home/Light/LED4/val\", payload: msg.payload[4] },\n        { topic: \"Home/Light/LED4/h\", payload: msg.payload[5] },\n        { topic: \"Home/Light/LED4/s\", payload: msg.payload[6] },\n        { topic: \"Home/Light/LED4/l\", payload: msg.payload[7] },   \n        { topic: \"Home/Light/LED4/w\", payload: msg.payload[8] },\n        { topic: \"Home/Sensor/HotWaterPulse\", payload: msg.payload[9] },\n        { topic: \"Home/Sensor/ColdWaterPulse\", payload: msg.payload[10] },        \n        { topic: \"Home/Power/Relay18/q\", payload: msg.payload[45] },\n        { topic: \"Home/Power/Relay18/command\", payload: msg.payload[46] },\n        { topic: \"Home/Power/Relay19/q\", payload: msg.payload[47] },\n        { topic: \"Home/Power/Relay19/command\", payload: msg.payload[48] },\n        { topic: \"Home/Power/Relay20/q\", payload: msg.payload[49] },\n        { topic: \"Home/Power/Relay20/command\", payload: msg.payload[50] },\n        { topic: \"Home/Power/Relay21/q\", payload: msg.payload[51] },\n        { topic: \"Home/Power/Relay21/command\", payload: msg.payload[52] },\n        { topic: \"Home/Power/Frame1/pos\", payload: msg.payload[73] },\n        { topic: \"Home/Power/Frame1/target\", payload: msg.payload[74] },    \n        { topic: \"Home/Power/Frame1/state\", payload: msg.payload[75] },     \n        { topic: \"Home/Power/Frame2/pos\", payload: msg.payload[76] },\n        { topic: \"Home/Power/Frame2/target\", payload: msg.payload[77] },    \n        { topic: \"Home/Power/Frame2/state\", payload: msg.payload[78] },\n        { topic: \"Home/Power/Frame3/pos\", payload: msg.payload[79] },\n        { topic: \"Home/Power/Frame3/target\", payload: msg.payload[80] },    \n        { topic: \"Home/Power/Frame3/state\", payload: msg.payload[81] },\n        { topic: \"Home/Power/RollShutter/pos\", payload: msg.payload[82] },\n        { topic: \"Home/Power/RollShutter/target\", payload: msg.payload[83] },    \n        { topic: \"Home/Power/RollShutter/state\", payload: msg.payload[84] },\n        { topic: \"Home/Power/WindowCover/pos\", payload: msg.payload[88] },\n        { topic: \"Home/Power/WindowCover/target\", payload: msg.payload[89] },    \n        { topic: \"Home/Power/WindowCover/state\", payload: msg.payload[90] },\n        { topic: \"Home/Power/WindowCover/UP\", payload: msg.payload[91] },\n        { topic: \"Home/Power/WindowCover/DOWN\", payload: msg.payload[92] }\n    ];\n    break;\n}\n\n\n// send the whole array of msgs to the output port\nreturn [msgs];","outputs":1,"noerr":0,"x":750,"y":80,"wires":[["ad4a4b5f.87ae48","90504d10.c206","94ef3325.0a3bf"]]},{"id":"f757d3c4.e0ab3","type":"modbus-response","z":"6cb719ba.d8bff8","name":"","registerShowMax":"10","x":730,"y":160,"wires":[]},{"id":"94ef3325.0a3bf","type":"debug","z":"6cb719ba.d8bff8","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1170,"y":140,"wires":[]},{"id":"5acd90f.7aed97","type":"inject","z":"6cb719ba.d8bff8","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":80,"wires":[["36d79240.bacaee"]]},{"id":"5dccbfb9.f5b43","type":"modbus-response","z":"6cb719ba.d8bff8","name":"","registerShowMax":20,"x":920,"y":320,"wires":[]},{"id":"ec9855ee.c2e998","type":"function","z":"6cb719ba.d8bff8","name":"Prepare write adress and value","func":"var addr=0;\n\nswitch(msg.topic) {\n    case 'Home/Light/Dimmer1/command/write':\n        addr=2;\n        break;\n    case 'Home/Light/Dimmer1/val/write':\n        addr=3;\n        break;\n    case 'Home/Light/Dimmer2/command/write':\n        addr=5;\n        break;\n    case 'Home/Light/Dimmer2/val/write':\n        addr=6;\n        break;\n    case 'Home/Light/Dimmer3/command/write':\n        addr=8;\n        break;\n    case 'Home/Light/Dimmer3/val/write':\n        addr=9;\n        break;\n    case 'Home/Light/Dimmer4/command/write':\n        addr=11;\n        break;\n    case 'Home/Light/Dimmer4/val/write':\n        addr=12;\n        break;\n    case 'Home/Light/Dimmer5/command/write':\n        addr=14;\n        break;\n    case 'Home/Light/Dimmer5/val/write':\n        addr=15;\n        break;\n    case 'Home/Light/Dimmer6/command/write':\n        addr=17;\n        break;\n    case 'Home/Light/Dimmer6/val/write':\n        addr=18;\n        break;\n    case 'Home/Light/Dimmer7/command/write':\n        addr=20;\n        break;\n    case 'Home/Light/Dimmer7/val/write':\n        addr=21;\n        break;        \n    case 'Home/Light/Dimmer8/command/write':\n        addr=23;\n        break;\n    case 'Home/Light/Dimmer8/val/write':\n        addr=24;\n        break;\n    case 'Home/Light/Dimmer9/command/write':\n        addr=26;\n        break;\n    case 'Home/Light/Dimmer9/val/write':\n        addr=27;\n        break;\n    case 'Home/Light/Dimmer10/command/write':\n        addr=29;\n        break;\n    case 'Home/Light/Dimmer10/val/write':\n        addr=30;\n        break;\n    case 'Home/Light/Dimmer11/command/write':\n        addr=32;\n        break;\n    case 'Home/Light/Dimmer11/val/write':\n        addr=33;\n        break;        \n    case 'Home/Light/Dimmer12/command/write':\n        addr=35;\n        break;\n    case 'Home/Light/Dimmer12/val/write':\n        addr=36;\n        break;        \n    case 'Home/Light/Dimmer13/command/write':\n        addr=38;\n        break;\n    case 'Home/Light/Dimmer13/val/write':\n        addr=39;\n        break;\n    case 'Home/Light/Dimmer14/command/write':\n        addr=41;\n        break;\n    case 'Home/Light/Dimmer14/val/write':\n        addr=42;\n        break;\n    case 'Home/Light/Relay1/command/write':\n        addr=53;\n        break;\n    case 'Home/Light/Relay2/command/write':\n        addr=55;\n        break;\n    case 'Home/Light/Relay3/command/write':\n        addr=57;\n        break;         \n    case 'Home/Light/Relay4/command/write':\n        addr=59;\n        break;         \n    case 'Home/Light/Relay5/command/write':\n        addr=61;\n        break;         \n    case 'Home/Light/Relay6/command/write':\n        addr=63;\n        break;         \n    case 'Home/Light/Relay7/command/write':\n        addr=65;\n        break;\n    case 'Home/Light/Relay8/command/write':\n        addr=67;\n        break;         \n    case 'Home/Light/Relay9/command/write':\n        addr=69;\n        break;         \n    case 'Home/Light/Relay10/command/write':\n        addr=71;\n        break;\n    case 'Home/Light/Relay11/command/write':\n        addr=73;\n        break;\n    case 'Home/Light/Relay12/command/write':\n        addr=75;\n        break;         \n    case 'Home/Light/LED1/command/write':\n        addr=83;\n        break;         \n    case 'Home/Light/LED1/val/write':\n        addr=84;\n        break;  \n    case 'Home/Light/LED1/h/write':\n        addr=85;\n        break;      \n    case 'Home/Light/LED1/s/write':\n        addr=86;\n        break; \n    case 'Home/Light/LED1/l/write':\n        addr=87;\n        break;     \n    case 'Home/Light/LED1/w/write':\n        addr=88;\n        break; \n    case 'Home/Light/LED2/command/write':\n        addr=90;\n        break;         \n    case 'Home/Light/LED2/val/write':\n        addr=91;\n        break;  \n    case 'Home/Light/LED2/h/write':\n        addr=92;\n        break;      \n    case 'Home/Light/LED2/s/write':\n        addr=93;\n        break; \n    case 'Home/Light/LED2/l/write':\n        addr=94;\n        break;     \n    case 'Home/Light/LED2/w/write':\n        addr=95;\n        break;    \n    case 'Home/Light/LED3/command/write':\n        addr=97;\n        break;         \n    case 'Home/Light/LED3/val/write':\n        addr=98;\n        break;  \n    case 'Home/Light/LED3/h/write':\n        addr=99;\n        break;      \n    case 'Home/Light/LED3/s/write':\n        addr=100;\n        break; \n    case 'Home/Light/LED3/l/write':\n        addr=101;\n        break;     \n    case 'Home/Light/LED3/w/write':\n        addr=102;\n        break;\n    case 'Home/Light/LED4/command/write':\n        addr=104;\n        break;         \n    case 'Home/Light/LED4/val/write':\n        addr=105;\n        break;  \n    case 'Home/Light/LED4/h/write':\n        addr=106;\n        break;      \n    case 'Home/Light/LED4/s/write':\n        addr=107;\n        break; \n    case 'Home/Light/LED4/l/write':\n        addr=108;\n        break;     \n    case 'Home/Light/LED4/w/write':\n        addr=109;\n        break;    \n    case 'Home/Power/Relay18/command/write':\n        addr=147;\n        break;\n    case 'Home/Power/Relay19/command/write':\n        addr=149;\n        break;    \n    case 'Home/Power/Relay20/command/write':\n        addr=151;\n        break;    \n    case 'Home/Power/Relay21/command/write':\n        addr=153;\n        break;    \n    case 'Home/Power/Frame1/target/write':\n        addr=175;\n        break;\n    case 'Home/Power/Frame2/target/write':\n        addr=178;\n        break;\n    case 'Home/Power/Frame3/target/write':\n        addr=181;\n        break;\n    case 'Home/Power/RollShutter/target/write':\n        addr=184;\n        break;\n    case 'Home/Power/WindowCover/target/write':\n        addr=190;\n        break;          \n}\n\nif (addr>0) {\nmsg.payload ={\n    value:msg.payload,\n'fc': 6,\n'unitid': 1,\n'address': addr ,\n'quantity': 1 }\nreturn msg;\n}","outputs":1,"noerr":0,"x":460,"y":320,"wires":[["39173ee3.afb182","823f2422.9b4338"]]},{"id":"8176a9e9.72d678","type":"comment","z":"6cb719ba.d8bff8","name":"Write to mobdbus","info":"","x":100,"y":260,"wires":[]},{"id":"823f2422.9b4338","type":"modbus-flex-write","z":"6cb719ba.d8bff8","name":"","showStatusActivities":false,"showErrors":true,"server":"d54264c3.dde5e8","emptyMsgOnFail":false,"keepMsgProperties":false,"x":720,"y":320,"wires":[[],["5dccbfb9.f5b43"]]},{"id":"46d3f76f.33b298","type":"delay","z":"6cb719ba.d8bff8","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"50","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":230,"y":320,"wires":[["ec9855ee.c2e998"]]},{"id":"39173ee3.afb182","type":"debug","z":"6cb719ba.d8bff8","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":710,"y":280,"wires":[]},{"id":"507d2d40.1130b4","type":"mqtt in","z":"6cb719ba.d8bff8","name":"","topic":"Home/#","qos":"2","broker":"6f159f68.33fd","x":70,"y":320,"wires":[["46d3f76f.33b298","137622b7.5b7f4d"]]},{"id":"5a5088c.75b4a78","type":"mosca in","z":"6cb719ba.d8bff8","mqtt_port":1883,"mqtt_ws_port":8080,"name":"","username":"","password":"","dburl":"","x":550,"y":40,"wires":[[]]},{"id":"7631ecad.7c8694","type":"delay","z":"6cb719ba.d8bff8","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"25","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":370,"y":80,"wires":[["29ce1ddc.dd3252"]]},{"id":"137622b7.5b7f4d","type":"rbe","z":"6cb719ba.d8bff8","name":"","func":"rbe","gap":"","start":"","inout":"out","property":"payload","x":190,"y":420,"wires":[["1696c7e9.2a3cc8"]]},{"id":"1696c7e9.2a3cc8","type":"debug","z":"6cb719ba.d8bff8","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":350,"y":400,"wires":[]},{"id":"90504d10.c206","type":"delay","z":"6cb719ba.d8bff8","name":"","pauseType":"timed","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"10","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":980,"y":180,"wires":[["86604079.996eb"]]},{"id":"6f159f68.33fd","type":"mqtt-broker","z":"","name":"Remote connection","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"15","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"d54264c3.dde5e8","type":"modbus-client","z":"","name":"PCL","clienttype":"tcp","bufferCommands":true,"stateLogEnabled":false,"queueLogEnabled":false,"tcpHost":"192.168.1.110","tcpPort":"502","tcpType":"DEFAULT","serialPort":"/dev/ttyUSB","serialType":"RTU-BUFFERD","serialBaudrate":"9600","serialDatabits":"8","serialStopbits":"1","serialParity":"none","serialConnectionDelay":"100","unit_id":"1","commandDelay":"1","clientTimeout":"1000","reconnectOnTimeout":false,"reconnectTimeout":"2000","parallelUnitIdsAllowed":false}]`

**Comment by biancode** [comment]
@mastrikGit try to work with the units in parallel on tcp in your case - how does it work for you in parallel?

**Comment by biancode** [comment]
<img width="210" alt="image" src="https://user-images.githubusercontent.com/4369867/82757473-f660de00-9de0-11ea-9e33-eb1cfef078c4.png">
on TCP

**Comment by biancode** [comment]
please test with the new 5.13.1

**Comment by mastrikGit** [comment]
Updated, set setting as you suggest. Will write back tomorrow with results.

Thank you for fast replies!

**Comment by mastrikGit** [comment]
@biancode Thanks for fast fix. Uptime is more than 24hrs after update and no errors appear
