### ISSUE TITLE
Failed Connection to Modbus Master on EADDRNOTAVAIL kills Node-RED

### ISSUE THREAD

**Issue by Ikoth** [BiancoRoyal/node-red-contrib-modbus#208]
**I'm submitting a ...**  (check one with "x")

## Problem
 - ( X) bug report => please search github for a similar issue or PR and test Modbus problems with the [modbus-serial](https://github.com/yaacov/node-modbus-serial) package before submitting
 - ( ) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
 If the ModbusServer node is unable to contact the defined Modbus Master server, it crashes Node Red.

 **Expected behavior**
 Don't kill Node red, just give a meaningful error.
 
 **Minimal reproduction of the problem with instructions**
 
Flow as follows:
[{"id":"1e9c8db4.c44142","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"293beb12.b54dd4","type":"inject","z":"1e9c8db4.c44142","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":160,"wires":[["9f080a42.f8a9f8"]]},{"id":"f4dcd059.d10e5","type":"debug","z":"1e9c8db4.c44142","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":620,"y":160,"wires":[]},{"id":"9f080a42.f8a9f8","type":"modbus-server","z":"1e9c8db4.c44142","name":"OPenPLC","logEnabled":false,"hostname":"10.35.144.110","serverPort":10502,"responseDelay":100,"delayUnit":"ms","coilsBufferSize":"1024","holdingBufferSize":"1024","inputBufferSize":"1024","discreteBufferSize":"1024","showErrors":false,"x":380,"y":180,"wires":[["f4dcd059.d10e5"],[],[],[],[]]}]

Error message from the Node Red server console, produced as soon as the timestamp button is clicked:

11 Jun 16:19:17 - [info] Starting flows
11 Jun 16:19:17 - [info] Started flows
11 Jun 16:19:17 - [info] Server now running at http://127.0.0.1:1880/
11 Jun 16:22:10 - [info] Stopping flows
11 Jun 16:22:10 - [info] Stopped flows
11 Jun 16:22:10 - [info] Starting flows
11 Jun 16:22:10 - [info] Started flows
11 Jun 16:22:10 - [red] Uncaught Exception:
11 Jun 16:22:10 - Error: listen EADDRNOTAVAIL: address not available 10.35.144.110:10502
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1498:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
PS C:\Users\Administrator\AppData\Roaming\npm>

   1. 
   2. 
   3. 
   
### Your Environment
**Please tell us about your environment:**
OpenPLC running on a RaspberryPi controlling a simple 2 switch, one LED breadboard circuit

  * ( X) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) package global from source (using git clone)
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) as a global package (using npm i -g)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - ( X) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   : OpenPLC
     - Version: v3
     - Vendor :
     - Link   : https://github.com/thiagoralves/OpenPLC_v3
    
* **node-red-contrib-modbus version:** v5.13.2

* **Node:** (min. 10.x)
   `node --version` = v12.18

**Comment by biancode** [comment]
It is a Node-RED concept to crash on unhandled errors. This package follows Node-RED in that case. What is the state without a valid address - unknown or complex - so it stops. Feel free to send a pull request with your ideas of handling such errors see core-client and reopen ! ;)   btw there is a safe mode in node-red for such errors if you did some wrong configuration.

**Comment by Ekristoffe** [comment]
@biancode , i am sorry but I don't agree with the way you describe the error handling system of Node-RED.
Here is a quote of the official documentation:

> **Handling errors**
> Node-RED provides two ways for a node to report an error. It can either just write a message to the log or it can notify the runtime of the error and cause a flow to be triggered.
> 
> If the error is only written to the log, you will see the message in the Debug sidebar and log output, but you will not be able to create a flow to handle it. These are uncatchable errors.
> 
> If it does notify the runtime properly, then it is a catchable error that can be used to trigger an error-handling flow.
> 
> There is a third sort of error that can cause the Node-RED runtime to shutdown. These uncaughtException errors cannot be handled in the flow and are caused by bugs in nodes.
> 
> This guide describes each of these error types in more detail and shows what can be done to handle them.

I personally think it is cleaner to return something in a console / error log instead of killing the whole machine.
Having Node-RED crash at every error mean we lose the context each time. 
(Not the best option).
Does the core/library return error ? or just throw and goodbye ?

**Comment by biancode** [comment]
@Ekristoffe I discussed it with the core team and you can find that on slack. It was there address in use and here we have nearly the same situation. As I wrote I am open for pull requests.

**Comment by biancode** [comment]
@Ekristoffe what I remind is that I tried to catch, but it wont and Node-RED is crashing because it is a system error and not just software handling, but maybe I missed some at this point.

**Comment by biancode** [comment]
see https://nodejs.org/api/errors.html

**Comment by Ikoth** [comment]
Very helpful. Thanks.

**Comment by biancode** [comment]
With v3.0.x of node-red we decided to handle errors in our package from v5.22.x+
