### ISSUE TITLE
Modbus client info from a function node

### ISSUE THREAD

**Issue by Kartheek1512** [BiancoRoyal/node-red-contrib-modbus#214]
**I'm submitting a ...**  (check one with "x")

## Feature
 - (x ) feature request
 
 **What is the motivation / use case for changing the behavior?**

I have 10 Pis.  Each Pi is pulling data from a power meter with unique IP address.  I want to have the modbus client details like IP address and Port saved in a file in the Pi. I then want to use a same node-red flow for all 10 different pis. The modbus flex getter has to pull the Modbus client details from the file and start pulling data from power meter

### Your Environment
**Please tell us about your environment:**

  * ( ) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) package global from source (using git clone)
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) as a global package (using npm i -g)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - ( ) Windows: v 
    - (x ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   :  Energy tracking power meter
     - Version:  
     - Vendor :  Energy tracker
     - Link   : https://
    
* **node-red-contrib-modbus version:** vX.X.X

* **Node:** (min. 10.x)
   `node --version` = v0.19.4

**Comment by biancode** [comment]
node v0.19.4 is not supported ;)

**Comment by biancode** [comment]
reopen with the requested information
