### ISSUE TITLE
Modbus limited to 16 bits holding register data input/output

### ISSUE THREAD

**Issue by CPW100** [BiancoRoyal/node-red-contrib-modbus#228]
**I am submitting an issue related to Modbus read/write feature limiting the number of bits an input/output data can be transmitted/received between Node-red platform and other devices.**

## Feature Request
 - Add a setting into the Modbus read/write nodes so that the data input/output is not limited to 16 bits number (i.e. number range between 0-65535) meaning it can read/write 32-bit or 64-bit floating-point number.
 
 **What is the motivation/use case for changing the behavior?**

The device that I am trying to connect to the Node-red platform supports the Modbus feature, however, the data output from the coil, holding, discrete input, and input registers are all in floating-point format. The software uses Lua language as the programming language, according to the documentation of Lua, the floating points can be either 32-bit or 64-bit format. 
 
 
 **Current behavior**
 
The Modbus read node is connected to the external controller but the Modbus-read node cannot interpret the data output from the external controller because the data output is a floating-point which is either 32-bit or 64-bit. Here is the error message displayed after deploying the flow:
*Client -> startIntervalReading node 8ae568bc.bddba8undefined*
 
 **Expected behavior**
 
The Modbus can display the data output (coil, input, discrete input, and holding register) from the external controller successfully using the debug node or Modbus Response node.
 
 **Minimal reproduction of the problem with instructions**
 
Since I connected Node-red to an external controller to read from or write to, and the data output from the controller is in floating-point, I am not sure if there is any other way to recreate the error.
   
### Your Environment
**Please tell us about your environment:**

  * ( ) I have installed [all in one Modbus TCP and Serial contribution package for Node-RED](https://flows.nodered.org/node/node-red-contrib-modbus) as a global package (using npm install -g node-red-contrib-modbus)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device 
  
    - ( ) Windows: version 10.0.19042 Build 19042
    
* **node-red-contrib-modbus version:** v5.13.3

**Comment by biancode** [comment]
Thanks for the issue - the Modbus nodes provide an IO config as expected, but it is on your side to do the configuration. The buffer is given from the nodes and you do all you need vie Buffer operations inside the flow as well.
