### ISSUE TITLE
The Modbus client crashes the node-red by using a serial port

### ISSUE THREAD

**Issue by a1664670118** [BiancoRoyal/node-red-contrib-modbus#241]
JSON：
[{"id":"43823a85.a79794","type":"modbus-read","z":"b9b55480.761308","name":"","topic":"","showStatusActivities":false,"logIOActivities":false,"showErrors":false,"unitid":"","dataType":"HoldingRegister","adr":"0","quantity":"10","rate":"1","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"e9a5d7bd.904e48","useIOFile":false,"ioFile":"","useIOForPayload":false,"emptyMsgOnFail":false,"x":380,"y":260,"wires":[["296bd1f4.65382e"],[]]},{"id":"e9a5d7bd.904e48","type":"modbus-client","name":"COM4","clienttype":"simpleser","bufferCommands":true,"stateLogEnabled":false,"queueLogEnabled":false,"tcpHost":"127.0.0.1","tcpPort":"502","tcpType":"DEFAULT","serialPort":"COM4","serialType":"RTU-BUFFERD","serialBaudrate":"9600","serialDatabits":"8","serialStopbits":"1","serialParity":"none","serialConnectionDelay":"100","unit_id":"1","commandDelay":"1","clientTimeout":"1000","reconnectOnTimeout":true,"reconnectTimeout":"2000","parallelUnitIdsAllowed":true}]
console.log
29 Mar 09:54:23 - Error: Could not locate the bindings file. Tried:
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\build\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\build\Debug\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\build\Release\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\out\Debug\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\Debug\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\out\Release\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\Release\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\build\default\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\compiled\12.20.2\win32\x64\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\addon-build\release\install-root\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\addon-build\debug\install-root\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\addon-build\default\install-root\bindings.node
 → E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\lib\binding\node-v72-win32-x64\bindings.node
    at bindings (E:\git\node-red-contrib-modbus\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\lib\win32.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\git\node-red-contrib-modbus\node_modules\modbus-serial\node_modules\@serialport\bindings\lib\index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red@1.2.9 start: `node packages/node_modules/node-red/red.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red@1.2.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by biancode** [comment]
please, reopen with filled template and more details if needed
