### ISSUE TITLE
Modebus-Flex-Getter Node stops working every few hours - "initialize"

### ISSUE THREAD

**Issue by rucksman** [BiancoRoyal/node-red-contrib-modbus#245]
My Flex-Getter node stops working every few hours, sometimes after one or two days. It then only says "initialize". The problem has to be within node-red-contrib-modbus as a php script which logs data into a database from the same modbus device works without problems.

The workaround/solution is:

- log into Node Red
- open the flow
- open the flex-getter node
- open the modbus server
- change some small detail (usually "Queue delay (ms)" one ms up or down)
- update modbus server with this new setting
- close flex-getter node
- deploy

Flex-Getter node immediately changes it's state to "active" and data is coming in.

So if there is no approach to avoid flex-getter to stop working: Is there a way to automatically "restart" the connection like I always do manually?

**Comment by biancode** [comment]
You could try the Status node to solve it. Mostly such a behaviour lays in too much reads or too fast reading to one node or wrong flow designs. Maybe you could provide an overview of your physical reads and timing per Modbus Connection and Node, please?

Please, reopen if you need ore and fill out the template questions. We need version information and more about to reproduce it!
