### ISSUE TITLE
node-red-contrib-modbus running problem with electron-node-red

### ISSUE THREAD

**Issue by jasonlee9900** [BiancoRoyal/node-red-contrib-modbus#257]
I'm submitting a problem with node-red-contrib-modbus running problem with electron-node-red  (check one with "x")

## Support/Advice
 - support/advice request => **Please do not submit support requests here**, instead use [the link to our support page](https://bianco-royal.space/supporter/), please!

## Feature
 - ( ) feature request
 
 **What is the motivation / use case for changing the behavior?**
 

## Simple question to get some hint
 - ( ) simple question => please visit the Wiki, the YouTube tutorials and the Info tab by clicking on the node inside Node-RED before
 - (x) help wanted => you read all information and watched relevant YouTube tutorials, but you need more help

## Problem
 - ( ) bug report => node-red-contrib-modbus running problem with electron-node-red
 - ( ) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
 
node-red-contrib-modbus work well on node-red platform, but node-red-contrib-modbus can not reconnect with device after 
 packed by electron-node-red. all other nodes can be packed and work well by electron-node-red except node-red-contrib-modbus. I do not think this is node-red-contrib-modbus design problem, but I'd like to debug it to find out what's problem why node-red-contrib-modbus can't be packed correctly, so I ask where is the code related function to make node-red-contrib-modbus always keep live whether device is online or not online.  
you may see my problem here:  https://github.com/dceejay/electron-node-red/issues/16

 **Expected behavior**
 
 
 **Minimal reproduction of the problem with instructions**
 
   1. 
   2. 
   3. 
   
### Your Environment
**Please tell us about your environment:**

  (x ) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
   ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) package global from source (using git clone)
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) as a global package (using npm i -g)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - (x) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   : Siemens PLC, S7-1200
     - Version: 4.0
     - Vendor : Siemens
     - Link   : https://
    
* **node-red-contrib-modbus version:** v5.14.0

* **Node:** (v14.x)
   `node --version` = vv12.19.0

**Comment by biancode** [comment]
We have no Windows - we support Linux and macOS only - Sorry
