### ISSUE TITLE
change IP host from msg

### ISSUE THREAD

**Issue by ketpa** [BiancoRoyal/node-red-contrib-modbus#279]
I want set from my database IP HOST for modbus TCP.
I try $host, msg.host and its doesn't work.

![obraz](https://user-images.githubusercontent.com/13816046/142210077-0d0b5b48-5425-4ea8-a024-84068f30cabf.png)

**Comment by biancode** [comment]
@ketpa it needs to handle the new connection - please use the flex connector in such cases ;)

**Comment by biancode** [comment]
reopen if there are more questions, please
