### ISSUE TITLE
Modbus ASCII Serial not working

### ISSUE THREAD

**Issue by GrtVHecke** [BiancoRoyal/node-red-contrib-modbus#290]
**I'm submitting a ...**  (check one with "x")

## Problem
 - (x ) bug report => please search github for a similar issue or PR and test Modbus problems with the [modbus-serial](https://github.com/yaacov/node-modbus-serial) package before submitting
 - ( ) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
I have a connection to an RS-485 device that supports both Modbus ASCII and Modbus RTU (depending on a dispswitch). In Modbus RTU connection, the device answers and I am able to read out all registers. In ModBUS ASCII mode I do not receive any data form the device (with the correct dip switch set). When I try the same with ModbusPoll (https://www.modbustools.com/modbus_poll.html) I can read out the registers.
 
 **Expected behavior**
Modbus ASCII should function as well.
 
 **Minimal reproduction of the problem with instructions**
   1.  Connect to a Mdobus ASCII device
   2. Read out regsiters
   3. You will get a timeout
   
### Your Environment
**Please tell us about your environment:**

  * ( x) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) package global from source (using git clone)
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) as a global package (using npm i -g)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    
    - ( ) macOS: v 
    - ( x) Linux: v10 (buster) - Debian
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   : ApexR5
     - Version: 1.05
     - Vendor : Lighthouse
     - Link   : https://www.golighthouse.com/en/airborne-particle-counters/apex-r5
    
* **node-red-contrib-modbus version:** v5.14.0

* **Node:** (v12.22.1)
   `node --version` = v12.22.1

**Comment by OlivierVerhaegen** [comment]
Duplicate: #277 already fixed
