### ISSUE TITLE
MODBUS-Flex-Getter-Node FSM state errors intermittently

### ISSUE THREAD

**Issue by AustinEcowerks** [BiancoRoyal/node-red-contrib-modbus#294]
**I'm submitting a ...**  (check one with "x")

## Simple question to get some hint
 
 - (X) help wanted => you read all information and watched relevant YouTube tutorials, but you need more help

## Problem
 - (X) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
The node in node-red will sometimes start giving errors, going through some states. 
"FSM failed > broken > reconnect > init > connected"
Sometimes it does not reconnect and cycles through all the states prior to connect. 
 
 **Expected behavior**
Not give state errors when operating under normal conditions
 
 **Minimal reproduction of the problem with instructions**
 It happens randomly and intermittently.  

   
### Your Environment
**Please tell us about your environment:**
 Opto 22 Groov Epic/Node-red (version 1.0.3) 

  * ( X) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    

    - (X ) Other:
         - Name:Opto 22 Groov Epic
         - Version:
   
 **node-red-contrib-modbus version:** v5.16.0

Here is what happens in debug:
`2/8/2022, 4:30:57 PMnode: VFD MODBUS
msg : string[123]
"Client -> fsm failed state after sending Get More About It By Logging Serial@/dev/ttySerMod0.0:9600bit/s default Unit-Id: 1"

2/8/2022, 4:31:42 PMnode: VFD MODBUS
msg : string[122]
"Client -> fsm broken state after failed Get More About It By Logging Serial@/dev/ttySerMod0.0:9600bit/s default Unit-Id: 1"

2/8/2022, 4:31:42 PMnode: VFD MODBUS
msg : string[125]
"Client -> fsm reconnect state after broken Get More About It By Logging Serial@/dev/ttySerMod0.0:9600bit/s default Unit-Id: 1"

2/8/2022, 4:31:44 PMnode: VFD MODBUS
msg : string[97]
"Client -> fsm init state after reconnecting Serial@/dev/ttySerMod0.0:9600bit/s default Unit-Id: 1"

2/8/2022, 4:24:49 PM node: VFD MODBUS
msg : string[83]
"Client -> fsm init in 2000 ms Serial@/dev/ttySerMod0.0:9600bit/s default Unit-Id: 1"

2/8/2022, 4:31:46 PMnode: VFD MODBUS
msg : string[125]
"Client -> fsm connected after state opened Get More About It By Logging Serial@/dev/ttySerMod0.0:9600bit/s default Unit-Id: 1"`

**Comment by AustinEcowerks** [comment]
it is similar to this thread:
https://github.com/BiancoRoyal/node-red-contrib-modbus/issues/236

**Comment by AustinEcowerks** [comment]
Still having this issue, maybe somebody could tell me how to better optimize my flow?
`
https://github.com/AustinEcowerks/Node-Red/blob/main/Flow
`
![Screen Shot 2022-02-22 at 8 50 39 AM](https://user-images.githubusercontent.com/100158899/156003814-a7e5be1d-3161-4a88-b176-3d514e2cc88d.png)

![Screen Shot 2022-02-22 at 8 50 02 AM](https://user-images.githubusercontent.com/100158899/156003824-c214f3f6-2608-4d59-b59d-ec6858ead44f.png)

**Comment by biancode** [comment]
"FSM failed" is not under normal condition for me - with that message it has a failure

**Comment by biancode** [comment]
@AustinEcowerks in the most cases users try to read or write (communicate) directly after the deploy, but in the physical world this doesn't work and produces failures while the flow engine starts. The device has to be connected with state active, what can consume some time depending on the device(s) and the Modbus implementation of the device(s). For that issue we contributed to the Inject node, long time before, to provide some start delay. The best practice here is it to set some second(s) before the first injects will be started.

**Comment by biancode** [comment]
see also #244

**Comment by biancode** [comment]
**Follow-up (stale-closed) — please verify on `node-red-contrib-modbus@5.46.0` (npm)**

This issue was closed by the stale bot without verified confirmation. The **“Modbus Failure On State sending” / FSM send-path** cluster was a target of the v5.46.0 client FSM hardening ([CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

```bash
npm i node-red-contrib-modbus@5.46.0
```

Please test and reply ✅ / ❌, **reopen**, or open a **new** issue. Thanks.
