### ISSUE TITLE
Output descriptions are "wrong"

### ISSUE THREAD

**Issue by hoegge** [BiancoRoyal/node-red-contrib-modbus#299]
## Problem

The description of outputs of the getters are the same for output 1 and output 2, which is not the case. I have tried to describe better for one of the nodes in PR.

PR: #300

**Comment by biancode** [comment]
The outputs should be the same, but msg[0] and msg[1] should be switched for the response node.

**Comment by biancode** [comment]
The mistake was implemented with the IO merge into this package. There is more work tbd.
