### ISSUE TITLE
Error: Port Not Open

### ISSUE THREAD

**Issue by JorgeAlberto91MS** [BiancoRoyal/node-red-contrib-modbus#307]
**I'm submitting a ...**  (check one with "x")

## Support/Advice
 - support/advice request => **Please do not submit support requests here**, instead use [the link to our support page](https://bianco-royal.space/supporter/), please!

## Feature
 - ( ) feature request
 
 **What is the motivation / use case for changing the behavior?**
 

## Simple question to get some hint
 - ( ) simple question => please visit the Wiki, the YouTube tutorials and the Info tab by clicking on the node inside Node-RED before
 - ( ) help wanted => you read all information and watched relevant YouTube tutorials, but you need more help

## Problem
 - (x) bug report => please search github for a similar issue or PR and test Modbus problems with the [modbus-serial](https://github.com/yaacov/node-modbus-serial) package before submitting
 - (x) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
 
If only exist Modbus flex-getter on the flows, when a consult to slave device is made, the debug window shows Error: Port not Open
 
 **Expected behavior**
 
 
 **Minimal reproduction of the problem with instructions**
 
   1. Use only flex-getter nodes.
   2. Make a consult to slave device.
   3. If a "Modbus Read" node is used the problem dissapear. 
   
### Your Environment
**Please tell us about your environment:**

  * ( x) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) package global from source (using git clone)
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) as a global package (using npm i -g)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    
    - (x) macOS: v 
    - (x) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name: 
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   : 
     - Version:
     - Vendor :
     - Link   : https://
    
* **node-red-contrib-modbus version:** vX.X.X

* **Node:** (v14.x)
   `node --version` = vX.X.X

**Comment by biancode** [comment]
Normally there should be no difference. All nodes using the client (config-node) to handle the connection and the connection handling is the work of the client node. Means a read node should get the same problem if you use the same client inside the nodes. 

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/4369867/182085521-65f50f3b-ff00-49b6-a7e3-ed8dd7af5e6d.png">

Test with just a flex-reader has no problem with a serial port client in test. The port was not to open, then I set the serial simulator to be ready again and the flex-getter can read well.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/4369867/182102202-a28e8e93-c3bd-4cff-b843-b5fbf1450764.png">

[flows.json.zip](https://github.com/BiancoRoyal/node-red-contrib-modbus/files/9232103/flows.json.zip)

Maybe you can make a short video to show the problem?
Happy wiring!

**Comment by biancode** [comment]
**Follow-up (stale-closed) — please verify on `node-red-contrib-modbus@5.46.0` (npm)**

This issue was closed by the stale bot without a verified fix. Client **FSM / reconnect / recovery** hardening in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) is intended to address this symptom class (silent stall, stuck `init`/`failed`/`broken`, reconnect after outage).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then reply with ✅ **fixed** / ❌ **still broken** (NR + Node.js versions + short state log), **reopen** this issue, or open a **new** issue if something else shows up. Reporter confirmation is the real close criterion.
