### ISSUE TITLE
possible to generate/interpret modbus packets ?

### ISSUE THREAD

**Issue by xjustbmw** [BiancoRoyal/node-red-contrib-modbus#322]
### Describe the requested feature

i have a gateway through mqtt that sends/receives modbus packets from a device
is it possible to generate/interpret modbus packets coming/going to mqtt using this ?

### Motivation

using this method to monitor devices connected on 4g -> rs485 adapter

**Comment by biancode** [comment]
The flex nodes are great for this.

**Comment by xjustbmw** [comment]
Im afraid none of the flex nodes cant do this directly

I ended up using a local port to send data to from flex getter. that port is then connected to mqtt out
then reply from mqtt in -> response to the local port :)
