### ISSUE TITLE
ModBus over RTU

### ISSUE THREAD

**Issue by M0DDer** [BiancoRoyal/node-red-contrib-modbus#332]
### Which node-red-contrib-modbus version are you using?

5.23.1

### What happened?

Version node-red-contrib-modbus 5.23.1
ModBus over RTU still works ONLY with "Telnet" selected
p,s. in my moxa converter RTU is selected (not telnet. telnet also avaliable here)

### Server

Other/External server

### How can this be reproduced?

Connect with RTU-over-TCP select "RTU-BUFFERED" and "TELNET"

### What did you expect to happen?

ModBus RTU ovet TCP works with "RTU-BUFFERED" selected

### Other Information

same issue in https://github.com/BiancoRoyal/node-red-contrib-modbus/issues/19

**Comment by biancode** [comment]
not to reproduce from our side
