### ISSUE TITLE
Suport for non standard function codes.

### ISSUE THREAD

**Issue by xury77** [BiancoRoyal/node-red-contrib-modbus#334]
### Describe the requested feature

Some devices using non standard function codes such as Sofar solar inverters. 
The Sofar inverter using FC 0x13 for writing inverter parameters. It will be nice to have ability to send even a raw binary data to device.
This protocol have a lot of function codes what is not possible to use with this node.

### Motivation

Using node-red-contrib-modbus with full access for non standard modbus devices.

**Comment by biancode** [comment]
Hi @xury77, check our Service [PLUS for Node-RED](http://nodered.plus/) for this feature request!

**Comment by biancode** [comment]
needs sponsors or more developers to help with the work
