### ISSUE TITLE
Breaks Node Red split join nodes

### ISSUE THREAD

**Issue by OlivierVerhaegen** [BiancoRoyal/node-red-contrib-modbus#336]
### Which node-red-contrib-modbus version are you using?

5.23.2

### What happened?

When updating to the newest version I noticed that this version breaks the split and join nodes by removing the `parts` property from the object.

![image](https://user-images.githubusercontent.com/56387556/194890087-d462ee91-a6ca-42d5-8ec9-ffc494fddf8a.png)

### Server

None/This is related to a node that doesn't connect to a server

### How can this be reproduced?

Connect split node before Modbus Flex Getter node and join node after.

### What did you expect to happen?

For the split/join operations to work like in version 5.21.2

**Comment by biancode** [comment]
Hi @OlivierVerhaegen, a flow would help to test. You can use the node-red-contrib-helper package to build a test fro our e2e testings. Please, insert comment what is expected inside the flow! Thank you in advance!

**Comment by OlivierVerhaegen** [comment]
Hi @biancode , I'm sorry I haven't been able to create an example flow lately because of busy times. I'll post it here when I get to it! 

My debugging tests showed that it might be a straight forward issue. The `parts` property is normally added to an object going through a split node (to be able to reconstruct the array after looping through it). When placing a Modbus flex getter node in the chain the `parts` property is removed from the object. This causes problems with reconstructing the array in the join node.

**Comment by unborn-andy** [comment]
Have you tried checking the Option "Keep Msg Properties" in the Modbus flex getter node ?

![image](https://user-images.githubusercontent.com/93290787/219970754-9d83f897-2ceb-4122-8399-24bca4deefd9.png)

**Comment by OlivierVerhaegen** [comment]
Hi Andy,

I may have been overlooking this checkmark.
Will try, thank you!
