### ISSUE TITLE
How to know what is the meaning of the status messages

### ISSUE THREAD

**Issue by VALERYRAMIREZ** [BiancoRoyal/node-red-contrib-modbus#339]
Hi, how are you?.

This time I'm asking how to know what is the mieaning of the status messages that prints the getter node or any other modbus node, I've seen the code here but it doesn't have any comment explaining the behavior that brings the specific status.

Thanks in advance for the help.

**Comment by biancode** [comment]
Hi, the node status is bind to the client and shows mostly the status of the client if show activities is active. Otherwise the node is very simple in showing its status.

**Comment by VALERYRAMIREZ** [comment]
Thanks for the clarification
