### ISSUE TITLE
Example Flow for Handling Scanning all possible or live RTUs

### ISSUE THREAD

**Issue by MachineSaver** [BiancoRoyal/node-red-contrib-modbus#341]
### Describe the requested feature

Request: An example flow that shows how a person could scan for live RTUs on a serial port.
Often in an application we have an unknown number of RTUs and I am trying to make a scanner that tries each RTU and saves the ones that respond into a global or flow variable.
I have tried using a loop and a catch node for dealing with RTU reads that timeout but have been unsuccessful in waiting for timeout, reconnect and making sure each request either:
1. Responds if the requested RTU is on the bus, saves the responding RTU to a variable (list) of live sensors.
2. Hits the timeout, reconnects to the port, and sends the next consecutive RTU to be checked.

Does anyone have an example of this or recommendations for how one could handle this?

### Motivation

Often in real applications we have an unknown number of RTUs on a bus.
I am trying to make a scanner that tries each RTU and saves the ones that respond into a global or flow variable.
It would be helpful to know from the developers the recommended approach for scanning for live RTUs.

**Comment by DirkBergmaier** [comment]
Hello,

would the Modbus Scanner Node also include the possibility to read the device indentification (FC 0x2B/0x0E) ?
Would it also be possible with the flex server node to write these device identification ?
Thank you in advance.
