### ISSUE TITLE
How to send variables to display in hmi siemens with modbus?

### ISSUE THREAD

**Issue by ahmedt04** [BiancoRoyal/node-red-contrib-modbus#357]
Hello,
i'm using node-red to get some variables from a plc via OpcUa i'm using an iot2050,
I managed to read the variables I need now I should send these variables to an hmi panel to be able to read them on the panel,
I have to do it in modbus, but I've never used modbus, does anyone know how to do it?
thank you.

**Comment by biancode** [comment]
hi @ahmedt04, you should have a register description (overview) about what is in the registers of the HMI. If so you can connect via Port 502 to your HMI or what ever is set to that device as the port and then you should be able to write via Node-RED inside the registers. There is maybe some more work to build the buffer of 16Bit to write in the register from strings or floats etc.
