### ISSUE TITLE
USB Connection

### ISSUE THREAD

**Issue by Abrechen2** [BiancoRoyal/node-red-contrib-modbus#386]
hey i've been trying to get a connection to my electricity meter with a usb to rs485 stick for ages. It just doesn't work I've tried 4 different sticks now, all sorts of settings, everything I've found.
I have the latest nodered and rasbian on a raspi 3b.
i am trying to get a connection with an eastron sdm72.
the sticks are all recognized and work under windows.
Can someone help me?

**Comment by Noschvie** [comment]
As a workaround you can use a RS485 to Ethernet converter and use it as Modbus TCP connection.
