### ISSUE TITLE
modbus flex server cannot be access from external modbus client

### ISSUE THREAD

**Issue by yichaoliang** [BiancoRoyal/node-red-contrib-modbus#407]
### Which node-red-contrib-modbus version are you using?

5.26.0

### What happened?

I tried to setup a simple modbus server in node red.
1. drag and drop a "Modbus Flex Server"
2. change the bind address to "127.0.0.1"
3. change the port to "502"
4. Coils remain as 50000, registers remains as 50000
5. start the flow

I used modscan to access the server locally, from the PC which has the node red installed. I can connect to the server if I connect via "127.0.0.1/502", but if I use the IP address of the PC "192.168.1.102/502", I cannot connect with the modbus server.
Then I tried from another PC, which is on the same subnet with ip address of "182.168.1.101" to access the server via modscan, modscan connection setting is "192.168.1.102/502", I cannot connect to the node red modbus server.

But when I disable the node red flow and used the "Modsim" to setup a modbus server on the same PC, I can connect to the modbus server either locally or remotely. By this testing, I can confirm the port 502 is opened on the server PC.

Please advise what further configuration I need to setup on the node red modbus server to allow remote access to the server?

many thanks

### Server

Modbus-Flex-Server Node (Please attach Script to the next section)

### How can this be reproduced?

json file attached

steps:
1. drag and drop a "Modbus Flex Server"
2. change the bind address to "127.0.0.1"
3. change the port to "502"
4. Coils remain as 50000, registers remains as 50000
5. start the flow

### What did you expect to happen?

successful remote access to the modbus server

**Comment by aquiot-inc** [comment]
I solved this issue by setting the server `Hostname` to the IP address of the Node Red instance serving the Modbus (in your case `192.168.1.102`).  With that, I can access the server from `192.168.1.102` both within the local Node Red (as `192.168.1.102`) and remotely from another instance of Node Red (also as `192.168.1.102`).
