### ISSUE TITLE
Modbus Flex Getter crashes Node-Red

### ISSUE THREAD

**Issue by Shadowwalker2412** [BiancoRoyal/node-red-contrib-modbus#408]
### Which node-red-contrib-modbus version are you using?

5.26.0

### What happened?

every few days, Node-Red crashes.
Now i found out in the syslog that the cause is the Modbus Flex Getter.

here is a part of the syslog
[Syslog.txt](https://github.com/BiancoRoyal/node-red-contrib-modbus/files/12309494/Syslog.txt)

### Server

Modbus-Flex-Server Node (Please attach Script to the next section)

### How can this be reproduced?

as i could see, the problem is in this flow.

[Huawei.txt](https://github.com/BiancoRoyal/node-red-contrib-modbus/files/12309532/Huawei.txt)

**Comment by biancode** [comment]
Can I ask you to analyze more, what exactly the memory leak problem is in that case?
