### ISSUE TITLE
[Modbus Flex Getter] Queue is reset on timeout

### ISSUE THREAD

**Issue by AdrienAdB** [BiancoRoyal/node-red-contrib-modbus#409]
### Which node-red-contrib-modbus version are you using?

5.25

### What happened?

- Enable queuing
- Send messages by polling multiple unitIds (from 1 to 4)

```js
const registers = [
    {
        'fc': 4,
        'unitid': 1,
        'address': 0xD010,
        'quantity': 2,
    },
    {
        'fc': 4,
        'unitid': 2,
        'address': 0xD010,
        'quantity': 2,
    },
    {
        'fc': 4,
        'unitid': 3,
        'address': 0xD010,
        'quantity': 2,
    },
    {
        'fc': 4,
        'unitid': 4,
        'address': 0xD010,
        'quantity': 2,
    }
]

for (let index = 0; index < registers.length; index++) {
    msg.payload = registers[index];
    node.send(msg);    
}
```

- In normal conditions, devices will reply and data can be processed. OK.
- But if unitId 2 fails on timeout, client reconnects, but queue messages are being reset. Devices 3,4 won't be called.

I found way to quick fix by adding rate limiter before the modbus getter, however polling becomes too slow, expecially when you have 30+ devices on the bus.

Anyway to prevent queue reset on reconnect?

### Server

Modbus-Server Node

### How can this be reproduced?

Described above.

### What did you expect to happen?

Queue to no reset on timeout error

**Comment by biancode** [comment]
It gets a reset from the problem complexity of what is actual happened. You can handle it via your own queue in Node-RED in that case.

**Comment by biancode** [comment]
**v5.46.0 release note:** Queue/send-path improvements in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) (queue depth cap, message eviction, FSM send/recovery coordination).

Please upgrade to **5.46.0** and reopen with a minimal flow if this still occurs.

**Comment by biancode** [comment]
**Follow-up — `node-red-contrib-modbus@5.46.0` is published on npm**

Earlier note: this symptom was a target of the v5.46.0 client FSM / reconnect / queue hardening ([CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then:
- reply here with ✅ **fixed** or ❌ **still broken** (short repro + NR/Node versions), or
- **reopen** this issue, or
- open a **new** issue if you see a different regression

We treat reporter confirmation as the real close criterion — thank you.
