### ISSUE TITLE
modbus read can inject http request without bug

### ISSUE THREAD

**Issue by mjmokhtar** [BiancoRoyal/node-red-contrib-modbus#414]
### Describe the requested feature

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/108962994/7cf063b1-40bb-4192-bd45-aee9bb3b0d1e)

i have problem like that when i used modbus read like this pic

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/108962994/87c4581d-6cfc-4f0a-b1ba-8aa6646f964e)

### Motivation

i  hope my request can be solved

**Comment by mjmokhtar** [comment]
Antoher request modbus red can inject mysql or postgresql

**Comment by mjmokhtar** [comment]
same like in top question

**Comment by biancode** [comment]
Did you check the example for Modbus via HTTP in the Node-RED examples of the package if that works for you?

**Comment by mjmokhtar** [comment]
i've check but dint't work its still bug
