### ISSUE TITLE
Modbus read stop and poll value

### ISSUE THREAD

**Issue by ecsauto** [BiancoRoyal/node-red-contrib-modbus#418]
### Which node-red-contrib-modbus version are you using?

 v3.1.0

### What happened?

I tried to implement the modbus tcp to read the input from Moxa iologik . 1st issue I encountered was the modbus read would stop without the error. I need to recreate the plug-in or restart the iologik to get it work again. The other issue is why I get 8 value from the DI if I only specific only 1 value. 

Here is the capture of 2nd issue:-
![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/144394915/652cf2d4-66ac-4867-904a-cf875079d480)

### Server

Modbus-Server Node

### How can this be reproduced?

[
    {
        "id": "d091457d5d5fdba1",
        "type": "tab",
        "label": "Flow 2",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "1da8eadc2e28ea24",
        "type": "modbus-read",
        "z": "d091457d5d5fdba1",
        "name": "Read",
        "topic": "",
        "showStatusActivities": false,
        "logIOActivities": false,
        "showErrors": false,
        "showWarnings": true,
        "unitid": "1",
        "dataType": "Coil",
        "adr": "0000",
        "quantity": "1",
        "rate": "1",
        "rateUnit": "s",
        "delayOnStart": false,
        "startDelayTime": "",
        "server": "58cb7e6c7e3d393c",
        "useIOFile": false,
        "ioFile": "",
        "useIOForPayload": false,
        "emptyMsgOnFail": false,
        "x": 290,
        "y": 220,
        "wires": [
            [
                "6c95516ddeef6b45"
            ],
            []
        ]
    },
    {
        "id": "6c95516ddeef6b45",
        "type": "debug",
        "z": "d091457d5d5fdba1",
        "name": "debug 7",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 580,
        "y": 220,
        "wires": []
    },
    {
        "id": "58cb7e6c7e3d393c",
        "type": "modbus-client",
        "name": "modbus-tcp@192.168.3.100",
        "clienttype": "tcp",
        "bufferCommands": true,
        "stateLogEnabled": false,
        "queueLogEnabled": false,
        "failureLogEnabled": true,
        "tcpHost": "192.168.3.100",
        "tcpPort": "502",
        "tcpType": "DEFAULT",
        "serialPort": "/dev/ttyUSB",
        "serialType": "RTU-BUFFERD",
        "serialBaudrate": "9600",
        "serialDatabits": "8",
        "serialStopbits": "1",
        "serialParity": "none",
        "serialConnectionDelay": "100",
        "serialAsciiResponseStartDelimiter": "0x3A",
        "unit_id": "1",
        "commandDelay": "1",
        "clientTimeout": "1000",
        "reconnectOnTimeout": false,
        "reconnectTimeout": "2000",
        "parallelUnitIdsAllowed": true,
        "showWarnings": true,
        "showLogs": true
    }
]

### What did you expect to happen?

I expect the read function will not stop working. and value of DI can be specified by the programmer. Thanks for your help in advance.

**Comment by biancode** [comment]
**Follow-up (stale-closed) — please verify on `node-red-contrib-modbus@5.46.0` (npm)**

This issue was closed by the stale bot without a verified fix. Client **FSM / reconnect / recovery** hardening in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) is intended to address this symptom class (silent stall, stuck `init`/`failed`/`broken`, reconnect after outage).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then reply with ✅ **fixed** / ❌ **still broken** (NR + Node.js versions + short state log), **reopen** this issue, or open a **new** issue if something else shows up. Reporter confirmation is the real close criterion.
