### ISSUE TITLE
modbus with multiple unit / slave.

### ISSUE THREAD

**Issue by fprouvez** [BiancoRoyal/node-red-contrib-modbus#424]
hi everybody and thanks in advance (sorry for my poor english)

i have some troubles with my nodered 
i have two unit  but i can't read in this two unit. i read every thread, but nothing can help me. does someone give me a sample?

i use 2 flex getter , parallel que is off, when the two flex getter are active i can read on one, the second give me time out.
if i alternativly de-activated one of the two flex-getter ican read the value.

i try to use flex connector but it doesn not work.

may be some one can help me?

thanks

**Comment by biancode** [comment]
I think you need to use just one Flex-Getter to send the requests one by one or the sequencer. Reopen if you need more.
