### ISSUE TITLE
Write input register don‘t work

### ISSUE THREAD

**Issue by PeMi68** [BiancoRoyal/node-red-contrib-modbus#425]
### Which node-red-contrib-modbus version are you using?

5.27

### What happened?

If I try to write with function into input register, only write at adress 0 work. If I try to write to any other adress, no value is written.

### Server

Modbus-Server Node

### How can this be reproduced?

Try function with input from example.

**Comment by biancode** [comment]
Hi, Input Register can be write protected by the server - I think Holding Registers are better in your case.

**Comment by biancode** [comment]
I tested it and it works as expected and we have all basic features in e2e testings for every release by CI/CD.
