### ISSUE TITLE
Function Code 43

### ISSUE THREAD

**Issue by innoagg** [BiancoRoyal/node-red-contrib-modbus#429]
### Which node-red-contrib-modbus version are you using?

Latest

### What happened?

Is there a cheat to be able to use function code 43 or others? Is it intentional to filter certain function codes? Flex Getter will only accept common ones. 

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/11233095/47e71259-7e14-4d6b-9bba-f86b08c8eb88)

### Server

Modbus-Flex-Server Node (Please attach Script to the next section)

### How can this be reproduced?

Use a function code 43 in "payload.fc"

**Comment by biancode** [comment]
Hi, you can try the CustomFC node to test with but it needs some function around to handle the buffers and encapsulation

**Comment by innoagg** [comment]
I apologize for not seeing that node. I must have read right over it. I'll give it a shot.

**Comment by biancode** [comment]
right the name is in that version Modbus Flex FC
<img width="329" alt="image" src="https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/4369867/52abdacc-26a9-4aff-b95b-6015be38942e">
