### ISSUE TITLE
Modbus Nodes do not forward msg attributes

### ISSUE THREAD

**Issue by Malfed** [BiancoRoyal/node-red-contrib-modbus#440]
### Which node-red-contrib-modbus version are you using?

5.28.0

### What happened?

I'm expecting the modbus nodes to forward all msg attributes from the input to the output when they are not overwritten by new values. Existing attributes should retain. Currently a complete new message object is created, only keeping the input topic.

### Server

Other/External server

### How can this be reproduced?

I'll provide an easy example:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/24369031/2a107e90-f846-429b-8ade-7be9cddbb3f7)
[flows.json](https://github.com/BiancoRoyal/node-red-contrib-modbus/files/14144957/flows.json)

The inject node has an payload containing all necessary information for the modbus node. In addition I've set a topic and msg.Some and msg.Hello:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/24369031/f0e35e53-ebeb-45af-bd13-34244580201a)

As a result the output from the modbus node is a new message object containing only the given topic of "ExampleTopic", but missing the attributes "Some" and "Hello":

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/24369031/9ec664e2-8189-4cc6-9d8d-ae2343c00b24)

### What did you expect to happen?

I expect the output to contain everything given as an input as long as it's not overwritten (e.g. like "payload"). Why are the modbus nodes clearing up the attributes? Is there any reason for it? I'd like to use the modbus node combined with HTTP nodes. For this I need to forward the incoming HTTP attributes to the HTTP response, but with the modbus node eliminating the data this is not possible.

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/24369031/6013d75f-ab2a-4a30-8444-8881a42219e9)

**Comment by kommando828** [comment]
Modbus is only numeric, to pass ASCII data through a modbus register you first convert the ASCII character to a number. The number will be then held in the register to be read and then converted back to ASCII. So a modbus node does not need to process non numeric data.

**Comment by Malfed** [comment]
Thank you for your reply. I don't know if we are misunderstanding each other. I don't want to send my example values of msg.Some and msg.Hello to the modbus device/modbus server. I just want Node Red and the modbus node to retain that information and pass it to the output. The value "TopicExample" of msg.topic is retained and passed to the output - why is the value "World" of msg.Hello not passed to the output?

I've set up a second example to make it clear. I've got two different inputs going into one Modbus Flex Getter and want to split them up again after the modbus node:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/24369031/6f4b3c9c-f554-41f7-b950-d98874ceb50f)

At my inject nodes I've set msg.startingNode = "FromTopInject" for the top one and "FromBottomInject" for the lower one:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/24369031/21e63c31-de30-41cb-8e46-16828cb168bb)

Then I'd like the switch node to check this value and direct into the upper or lower way:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/24369031/bd1f2714-3c07-402a-b917-67dab472b0f4)

But this is not possible because msg.startingNode is no longer set. It is cleared by the modbus node and I don't understand why.

And before the suggestion comes up: Unfortunately, I cannot use msg.topic for my case.

**Comment by kommando828** [comment]
There is no requirement for normal modbus usage in what you ask, so it may be added by the developers but for a single user I doubt it will happen but they will reply. While waiting I would instead have a pre and post node. The pre node strips out your HTTP and then passes it directly to the post node missing out the modbus node to be recombined, the modbus continues into the modbus node. For the pre node you could use switch or filter, post node use change or join.

**Comment by Malfed** [comment]
I'm not that deep into NodeRed, but I thought it is normal behaviour to pass everything given from the input to the output, even it is not used by that single node. Until now every node I've used had exactly that behaviour, but the modbus nodes didn't.

I've had set up exactly your suggestion but I encountered some problems with splitting and rejoining, so I tried to work with a single line flow without splitting. If there will be no option to pass the values through I'll have to have a look at that solution again.

I'll wait for another response from the dev. Again, thank you :)

**Comment by kommando828** [comment]
I am not an expert either, currently at 4 complete and functioning flows started from scratch. The best way I find to get a flow to do what you want is to search the flow examples on the Node-red site and then import them for unpicking and altering, the ones that do what you are looking for are not always the obvious ones so a bit of hinting is needed. So for my MQTT to modbus flows I use a Json Filter node to extract single values from a full MQTT message.

https://flows.nodered.org/flow/7db69e532e4c58eb8078724092c4308a

**Comment by biancode** [comment]
HI, the flex-getter sends out a new msg every time and has an option to "keepMsgProperties" - HTTP should work as we have it in the examples - did you test the Modbus HTTP example, which is delivered with the package?

**Comment by Malfed** [comment]
Hi and thanks for your response. That's exactly what I need. To be honest I did not know that there are additional properties under that tab which would exactly solve my problem.

Sorry for wasting your time on this and thank you very much! :)

**Comment by biancode** [comment]
no worries 😎 feel free to help us to improve, how to find or learn better from our docs 😉
