### ISSUE TITLE
Global Configuration Node - Not Saving "Optionals" Settings

### ISSUE THREAD

**Issue by innoagg** [BiancoRoyal/node-red-contrib-modbus#442]
### Which node-red-contrib-modbus version are you using?

Latest

### What happened?

Attempting to de-select the "Show Error" and "Show Warnings" settings:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/11233095/22212476-ffb2-46db-89d3-5e43cb4ca971)

The selection is not saved and I continue to see messages in the debug. Are these intended to be non-configurable? 

### Server

Other/External server

### How can this be reproduced?

De-select the "Optionals" settings as shown in the image above. Deloy then return to the configuration node and observe the settings are still selected.

### What did you expect to happen?

Prefer to disable warnings and errors on demand to cleanup the debug output.

**Comment by biancode** [comment]
released in v5.30.0
