### ISSUE TITLE
Reconnect timeout for RTU slave behind gateway

### ISSUE THREAD

**Issue by JeroenVanHoye** [BiancoRoyal/node-red-contrib-modbus#446]
### Describe the requested feature

When an RTU slave does not respond, it would be nice if requests to this specific slave only are suspended until the "RTU reconnect" timeout has passed.

### Motivation

When polling multiple slaves behind a gateway at rapid pace and 1 slave is down, it interrupts all communications to this gateway.
It would be nice to have other communications go on as normal and only retry a timed out slave ID every minute or so (for example). 
I thought this would be a nice addition to the configuration menu, or should i cover this problem in my project code?

**Comment by biancode** [comment]
Just an idea, with a gateway you could try the parallel UintId option to communicate per UnitId. Some gateways can handle that. Let me know if that works for you!

**Comment by biancode** [comment]
**v5.46.0 release note:** Reconnect/deploy paths were improved in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) FSM hardening (`reconnecting` timer cleanup, `closingModbus` guards, preserved `reconnectTimeout` config).

Please upgrade to **5.46.0** and reopen with client type (TCP/serial), deploy steps, and state log if reconnect still fails.

**Comment by biancode** [comment]
**Follow-up — `node-red-contrib-modbus@5.46.0` is published on npm**

Earlier note: this symptom was a target of the v5.46.0 client FSM / reconnect / queue hardening ([CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then:
- reply here with ✅ **fixed** or ❌ **still broken** (short repro + NR/Node versions), or
- **reopen** this issue, or
- open a **new** issue if you see a different regression

We treat reporter confirmation as the real close criterion — thank you.
