### ISSUE TITLE
Modbus server hang if link down

### ISSUE THREAD

**Issue by vaniiplon** [BiancoRoyal/node-red-contrib-modbus#447]
### Describe the requested feature

As we are writing some values to modbus server which external device reads that data through TCP/IP. 
External device connects to it keeps on changing the port.
In that particular time when external device changes its port modbus server hangs and device lost communication
"ECONNREFUSED error"

Any solution to make server stable if once connection/link down

### Motivation

communication loss

**Comment by biancode** [comment]
Hi, which of the server do you mean here?

**Comment by vnvasireddy** [comment]
**modbus flex server**     in node-red **node-red-contrib-modbus package**
