### ISSUE TITLE
Auto reconnect upon re-establishing Ethernet connection between Flex server and Flex getter flows?

### ISSUE THREAD

**Issue by niranjanshukla** [BiancoRoyal/node-red-contrib-modbus#458]
### Which node-red-contrib-modbus version are you using?

5.30.0

### What happened?

I am testing the Modbus Flex Server reading sample flow as a consumer, and Modbus Simple servers as a server flow. Modbus flex server reading is deployed to a R-Pi. Modbus Simple servers is deployed on my windows computer. The R-Pi is connected to Windows computer over Ethernet (with static IPs assigned).

The test works as expected, but when I unplug the Ethernet connection, my Modbus Flex Getter node still shows as "Active", Automatic Read Flex FC3 shows as "Initialized". Subsequently, when I reconnect the Ethernet connection, the state of these nodes does not change and they do not seem to be receiving new data.

Upon unplugging the Ethernet connection, I believe the socket connection is not dropped? Normally, I have to restart my flows to be able to start receiving data. What could be done to receive data again without having to restart the flows?

### Server

Modbus-Flex-Server Node (Please attach Script to the next section)

### How can this be reproduced?

I am testing the Modbus Flex Server reading sample flow as a consumer, and Modbus Simple servers as a server flow. Modbus flex server reading is deployed to a R-Pi. Modbus Simple servers is deployed on my windows computer. The R-Pi is connected to Windows computer over Ethernet (with static IPs assigned).

The test works as expected, but when I unplug the Ethernet connection, my Modbus Flex Getter node still shows as "Active", Automatic Read Flex FC3 shows as "Initialized". Subsequently, when I reconnect the Ethernet connection, the state of these nodes does not change and they do not seem to be receiving new data.

**Comment by biancode** [comment]
**v5.46.0 release note:** Reconnect/deploy paths were improved in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) FSM hardening (`reconnecting` timer cleanup, `closingModbus` guards, preserved `reconnectTimeout` config).

Please upgrade to **5.46.0** and reopen with client type (TCP/serial), deploy steps, and state log if reconnect still fails.

**Comment by biancode** [comment]
**Follow-up — `node-red-contrib-modbus@5.46.0` is published on npm**

Earlier note: this symptom was a target of the v5.46.0 client FSM / reconnect / queue hardening ([CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then:
- reply here with ✅ **fixed** or ❌ **still broken** (short repro + NR/Node versions), or
- **reopen** this issue, or
- open a **new** issue if you see a different regression

We treat reporter confirmation as the real close criterion — thank you.
