### ISSUE TITLE
Modbus-Flex-Getter

### ISSUE THREAD

**Issue by wangganggit** [BiancoRoyal/node-red-contrib-modbus#463]
Modbus-Flex-Getter节点配置完，仅仅配置了两条链，还是间歇性报错 error: Error: Timed out\r\n","stream":"stdout","time":"2024-05-13T07:03:14.107663558Z"}
{"log":"      at /data/node_modules/node-red-contrib-modbus/modbus/maps/core/core/modbus-client-core.js:79:156\r\n","stream":"stdout","time":"2024-05-13T07:03:14.107666235Z"}
{"log":"      at runMicrotasks (\u003canonymous\u003e)\r\n","stream":"stdout","time":"2024-05-13T07:03:14.107671258Z"}
{"log":"      at runNextTicks (node:internal/process/task_queues:61:5)\r\n","stream":"stdout","time":"2024-05-13T07:03:14.107674209Z"}
{"log":"      at processTimers (node:internal/timers:499:9) {\r\n","stream":"stdout","time":"2024-05-13T07:03:14.107676949Z"}
{"log":"    nodeStatus: 'reconnecting after 2000 msec.'\r\n","stream":"stdout","time":"2024-05-13T07:03:14.107679601Z"}
{"log":"  },\r\n","stream":"stdout","time":"2024-05-13T07:03:14.107682227Z"}
{"log":"  _msgid: '3da5e42434c7b713'\r\n","stream":"stdout","time":"2024-05-13T07:03:14.107684721Z"}

**Comment by biancode** [comment]
**Follow-up (stale-closed) — please verify on `node-red-contrib-modbus@5.46.0` (npm)**

Closed by stale bot without verification. Intermittent **Timed out** in `modbus-client-core` / Flex-Getter was a primary target of v5.46.0 FSM + timeout hardening (see open #569 and [CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

```bash
npm i node-red-contrib-modbus@5.46.0
```

Please upgrade and reply ✅ / ❌, **reopen**, or open a **new** issue with NR/Node versions + log excerpt.
