### ISSUE TITLE
Modbus ASCII over TCP/IP not working

### ISSUE THREAD

**Issue by mrfy** [BiancoRoyal/node-red-contrib-modbus#469]
### Which node-red-contrib-modbus version are you using?

5.31.0

### What happened?

I am testing this library to read the Delta PLC DVP14SS2 controller, which operates in Modbus ASCII mode. I communicate with the controller using the USR-TCP232-410s RS232 / RS485 Ethernet converter. The Delta PLC controller is connected to the RS232 input of my converter.

I am reporting an issue because I am unable to read the controller's registers; in Node-Red, I receive the message 'Error: Timed Out', while comunication is set as TCP.

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/22953614/a2ca5198-bd6e-4aab-930f-0a975cec336f)

 For comparison, using the Modbus Poll program, I am able to read the controller correctly. For this configuration:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/22953614/a15abe3b-d7b2-428e-9678-a33fcb1aafc2)

When I connect the serial port from my laptop directly to the PLC controller and change the configuration in Node-Red to use the COM port and set the connection mode to ASCII, I can read the registers without any problems.

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/22953614/57a9f979-1464-44d2-8f8b-b983328bde9c)

I searched the forum but found two issues related to ASCII communication, but issues are related to serial connection. It appears that ASCII is unsupported in TCP mode.

### Server

Other/External server

### How can this be reproduced?

Trying to read modbus ASCII device using TCP/IP connection.

### What did you expect to happen?

Correctly read registers using TCP Modbus ASCII

**Comment by biancode** [comment]
Hi, if the serial settings of the Modbus poll are the defaults, then you need to set them as in Modbus poll via the Serial Expert  configuration type of the config node. Give it a try with the 7 data Bits, even parity and 1 stop Bit

**Comment by mrfy** [comment]
> Hi, if the serial settings of the Modbus poll are the defaults, then you need to set them as in Modbus poll via the Serial Expert configuration type of the config node. Give it a try with the 7 data Bits, even parity and 1 stop Bit

Thank you for response but I think we little misnundersood :)

Please take a look on Modbus Poll Read/Write Definition - I can correctly read modbus registers:
![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/22953614/90fe8eb3-2f99-4571-901c-3fb0ff243ee7)


Similar configuration in Node Red -  I cannot:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/22953614/8e50c604-8f4b-4aa3-bc5e-087502a5454d)
![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/22953614/34e3cb22-1017-42b1-b792-e0b5333276a5)


I hope that screens give you full view on the situation :)

**Comment by mrfy** [comment]
Hello, I have do more tests. And I think I know where is the issue. When I'm sending raw HEX modbus frame using TCP connection in node-red I have response:
![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/22953614/8f1a0579-5dbe-4b42-a115-4058050f5629)

Function, and response:

![image](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/22953614/5efe8a20-31ab-48c5-84d3-90bf3ba46033)

**Comment by biancode** [comment]
If you switch on more debugging in logs see Wiki Article [Debug]( https://github.com/BiancoRoyal/node-red-contrib-modbus/wiki/DEBUG) and start node-red with parameter -v (verbose) - then you should see what we send and what is the problem
