### ISSUE TITLE
node stop poll rate after 5 days

### ISSUE THREAD

**Issue by mjmokhtar** [BiancoRoyal/node-red-contrib-modbus#470]
### Which node-red-contrib-modbus version are you using?

5.31.0

### What happened?

node stop poll rate when after 5 day running in sever 

### Server

Modbus-Server Node

### How can this be reproduced?

i have my report in txt file using date time and nodes stop poll rate

### What did you expect to happen?

fix this and make running all time

**Comment by biancode** [comment]
Hi, a better description is needed here.

**Comment by biancode** [comment]
**v5.46.0 release note:** This symptom cluster was a target of client **FSM hardening** in [v5.46.0](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md) (reconnect timer guards, recovery from `broken`/`failed`/`reconnecting`, duplicate timer cleanup, jsmodbus error handler).

We are **not** marking this as verified fixed without reporter confirmation. Please upgrade to **5.46.0**, enable state logging if needed, and **reopen** with FSM state-log excerpts if the problem returns.

Related open tracking: #564, #569.

**Comment by biancode** [comment]
**Follow-up — `node-red-contrib-modbus@5.46.0` is published on npm**

Earlier note: this symptom was a target of the v5.46.0 client FSM / reconnect / queue hardening ([CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then:
- reply here with ✅ **fixed** or ❌ **still broken** (short repro + NR/Node versions), or
- **reopen** this issue, or
- open a **new** issue if you see a different regression

We treat reporter confirmation as the real close criterion — thank you.
