### ISSUE TITLE
Modbus-Flex-Connector error "setting 'nodeStatus'"

### ISSUE THREAD

**Issue by DyachenkoAlexey** [BiancoRoyal/node-red-contrib-modbus#474]
### Which node-red-contrib-modbus version are you using?

5.40.0

### What happened?

After updating node-red-contrib-modbus, Modbus-FlexConnector began to display the message "TypeError: Cannot set properties of undefined (setting 'nodeStatus')". Adding the "nodeStatus" parameter to the input message for configuring the port did not lead to positive results.

### Server

Modbus-Server Node

### How can this be reproduced?

Send new port settings to the input in accordance with the example to the node.

### What did you expect to happen?

The settings were applied as in previous versions. But now they don't work.

**Comment by MaryamJalil** [comment]
Hi @DyachenkoAlexey , Can you share your example flow for this issue in the comment too

**Comment by DyachenkoAlexey** [comment]
Hi. My solution is to go back to the previous version. My project requires changing the connection settings via dashboard.

**Comment by biancode** [comment]
I checked it and there was a bigger mistake from a merge - it will be fixed soon and brings some new tests and improvements.

**Comment by biancode** [comment]
fixed with version 5.41.0
