### ISSUE TITLE
FC20 Read File Record doesn't work

### ISSUE THREAD

**Issue by me21** [BiancoRoyal/node-red-contrib-modbus#477]
### Which node-red-contrib-modbus version are you using?

5.40.0

### What happened?

I'm trying to read file record using code 20 (14h). I use Modbus Flex-FC node for that. The device I'm querying is a real external device connected to a serial port over Modbus RTU.
I connected an oscilloscope to the serial lines and I can see the request and the response. But the response isn't correctly parsed.
Regular requests like read/write coils, holding registers, etc. are fine.

Request: F7 14 07 06 00 03 00 00 00 04 59 3B
Response: F7 14 0A 09 06 00 00 00 00 00 00 00 00 A2 3A

### Server

Other/External server

### How can this be reproduced?

I think it can be reproduced by trying to read file record from any server which supports that feature.

### What did you expect to happen?

A response should be correctly parsed.

### Other Information

The flow looks like this:

![изображение](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/807120/d5f87877-e82a-4943-bfd5-61f22d7a5bff)

I can provide any additional information you may need.

**Comment by biancode** [comment]
File record is special and not supported out-of-the-box - that why I see this more as a feature request at the moment

**Comment by me21** [comment]
I have a patch which I can share. But it's for @open-p4nr/modbus-serial package which is downloaded from a private repository if I'm correct. How do I submit it?

**Comment by me21** [comment]
@biancode please feel free to reopen it if it's not really completed.
