### ISSUE TITLE
Unexpexted behavior: msg.unitId turns into msg.unitid, when keep msg properties is set

### ISSUE THREAD

**Issue by Strunck** [BiancoRoyal/node-red-contrib-modbus#482]
### Which node-red-contrib-modbus version are you using?

5.41.0

### What happened?

The property `msg.unitId` changes to `msg.unitid`  (with small letter i), when Option "Keep Msg Properties" is set.

### Server

Other/External server

### How can this be reproduced?

Add debug node with `msg.unitId` after a Modbus-Flex-Sequencer and then change the Option "Keep Msg Properties".

### What did you expect to happen?

The msg Property `unitId` should not change.

### Other Information

Most all of the Modbus Response Properties seem to be CamelCase with the exception of `unitid`.
A consistent way is probably hard to determine. I would vote for CamelCase, since that is how the majority of properties are defined. And one can always expect `unitId` with capital `I`.

**Comment by biancode** [comment]
**v5.46.0:** `getActualUnitId()` now accepts both `unitId` and `unitid` on `msg.payload` (see #568). Reopen if `keepMsgProperties` still drops or renames fields in your specific node chain.

**Comment by biancode** [comment]
**Follow-up — `node-red-contrib-modbus@5.46.0` is published on npm**

Earlier note: this symptom was a target of the v5.46.0 client FSM / reconnect / queue hardening ([CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then:
- reply here with ✅ **fixed** or ❌ **still broken** (short repro + NR/Node versions), or
- **reopen** this issue, or
- open a **new** issue if you see a different regression

We treat reporter confirmation as the real close criterion — thank you.
